## Employment-Trends Data Prep

By Ken Burchfiel

Released under the MIT License

This notebook is used to calculate the employment metrics used by my interactive dashboard.

*Note: This script is a bit 'messy' at the moment, since while I originally wrote most of it using Pandas, I later switched to Polars for a number of operations due to its speed. Eventually, I might replace all of the Pandas code with Polars-based equivalents, but in the meantime, there's a lot of switching between the two libraries that makes the codebase a bit cluttered.*

In [1]:
# import gc
# gc.collect()

In [2]:
import time
start_time = time.time()
from datetime import datetime
import pandas as pd
pd.set_option('display.max_columns', 1000)
import plotly.express as px
import numpy as np
import svy # prerequisite: pip install svy within your Python environment
# The svy library allows us to analyze complex survey
# data. See https://svylab.com/docs/svy/.
import polars as pl
import gc
import os
from survey_analysis_functions import perform_svy_analysis, \
create_svy_reg, survey_pivot, pl_survey_pivot, import_stata_data
from polars_readstat import scan_readstat, ScanReadstat

Configuration variables:

In [3]:
run_svy_analyses = True # svy-based point-estimate and confidence-interval 
# calculations will only get run when this filter is set to True.
run_polars_analyses = True # an equivalent variable for Polars-based
# pivot-table analyses
#filename_substrings_to_redo = []
filename_substrings_to_redo = ['2026']
# When a filename containing 
# svy results is present within this list, a new version of that analysis
# will get rerun. (Normally, analyses are skipped when a corresponding
# result file is already present.) This variable will prove particularly 
# useful for updating data for the current year.

# Specifying which folder stores CPS files (in .dta) form:
# CPS data can be stored within one single file *or* as separate
# files (which makes incremental updates easier).
cps_file_folder = "/home/kjb3/D1V1/kjb3largefiles/\
large_programming/datasets/cps/source_files/"
# (Make sure ot add a slash at the end)

# Specifying folders that will store svy- and Pandas-based analyses:
svy_period_entry_file_folder = 'svy_period_entry_datasets'
polars_analyses_file_folder = 'polars_period_datasets'

In [4]:
## To do: Have the following cell use Polars, rather than Pandas, to import the dataset

Importing all CPS .dta files, then combining them into a singe DataFrame:

In [5]:
dfp_list = []

for cps_file in os.listdir(cps_file_folder):
    dfp_list.append(import_stata_data(cps_file_folder+cps_file,
    cols_to_convert_to_strings = ['occ2010']))

dfp = pl.concat([dfp for dfp in dfp_list], how = 'diagonal')
# This approach is similar to that I use for pd.concat().
# 'diagonal' allows DataFrames of different widths to be concatenated.

The DataFrame is 23488604 rows long.
The DataFrame is 91299 rows long.

Checking the number of *unique* CPS respondents each month: (Respondents are surveyed multiple times each year, so we can't simply add up the number of responses each year to arrive at this value.)

In [6]:
dfp.unique(['cpsidp', 'year']).group_by('year').len().sort('year')

shape: (17, 2)
┌──────┬────────┐
│ year ┆ len    │
│ ---  ┆ ---    │
│ i16  ┆ u32    │
╞══════╪════════╡
│ 2010 ┆ 504585 │
│ 2011 ┆ 499400 │
│ 2012 ┆ 496272 │
│ 2013 ┆ 494381 │
│ 2014 ┆ 504781 │
│ …    ┆ …      │
│ 2022 ┆ 403354 │
│ 2023 ┆ 395458 │
│ 2024 ┆ 390631 │
│ 2025 ┆ 379244 │
│ 2026 ┆ 312652 │
└──────┴────────┘

Note: I originally wrote the following code using Pandas, so although it would be faster to perform these operations in Polars, I'll keep them in Pandas for now. (I might rewrite them in Polars later on in order to speed up these cells.)

In [7]:
df = dfp.to_pandas()

Capitalizing the first letter of non-missing occupation responses so that they'll display better within our dashboard:

In [8]:
df['occ2010'] = np.where(df['occ2010'] != 'niu', df['occ2010'].str.capitalize(), df['occ2010'])

In [9]:
df['age_as_int'] = df['age'].astype('str').replace('under 1 year', '0').astype('int')

In [10]:
df['age_range'] = np.select(condlist = [df['age_as_int'] <= 21,
                      df['age_as_int'] <= 24,
                      df['age_as_int'] <= 29,
                      df['age_as_int'] <= 34,
                      df['age_as_int'] <= 39,
                      df['age_as_int'] <= 44,
                      df['age_as_int'] <= 49,
                      df['age_as_int'] <= 54,
                      df['age_as_int'] <= 59,
                      df['age_as_int'] >= 60],

          choicelist = ['21 or younger', # This was originally 'Under 
                        # 22,' but setting it to '21 or younger' will allow
                        # it to appear first when these items are sorted
                        # alphabetically--and, thus, first within our 
                        # legends.
                        '22-24',
                        '25-29',
                        '30-34',
                        '35-39',
                        '40-44',
                        '45-49',
                        '50-54',
                        '55-59',
                        '60 or older'],
          default = 'Missing age')

In [11]:
df['age_range'].value_counts()

age_range
21 or younger    6358672
60 or older      5709424
55-59            1599703
50-54            1593513
30-34            1526629
45-49            1510475
35-39            1508905
40-44            1501751
25-29            1449707
22-24             821124
Name: count, dtype: int64

In [12]:
df['quarter'] = df['month'].map({1:'Q1', 2:'Q1', 
3:'Q1', 4:'Q2', 5:'Q2', 6:'Q2', 7:'Q3', 8:'Q3',
9:'Q3', 10:'Q4', 11:'Q4', 12:'Q4'})

In [13]:
# df['quarter'].value_counts()

In [14]:
df['half'] = df['quarter'].map({'Q1':'H1', 'Q2':'H1', 'Q3':'H2', 'Q4':'H2'})

In [15]:
df['year_and_month'] = df['year'].astype('str')+'-'+df['month'].astype('str').str.zfill(2)

In [16]:
df['year_and_month'].value_counts()

year_and_month
2010-04    137208
2010-05    136572
2010-02    136231
2010-06    135840
2010-07    135788
            ...
2026-07     90719
2025-12     90366
2025-11     90299
2026-01     90297
2026-03     89319
Name: count, Length: 200, dtype: int64

## Creating an initial set of strata values:

(This approach was suggested by Ivan Strahof of IPUMS at https://forum.ipums.org/t/calculating-standard-errors-using-cps-basic-monthly-microdata/6408/7 . It's based on guidance from Davern et al. (2007). I'll soon create an updated version of these strata such that every stratum is found within all year-month pairs, which Ivan also recommended.)

In [17]:
df['stratum'] = df['placefips'].astype('str') + '_' + df['county'].astype(
'str') + '_' + df['statefip'].astype('str')

In [18]:
df.query("placefips != 0")['stratum'].value_counts()

stratum
50000_11001_11    231450
44000_6037_6      202327
14000_17031_17    116772
35000_48201_48    106103
55000_4013_4       79292
                   ...
81666_6095_6        3309
82590_6071_6        3221
64000_51740_51      2721
35000_51650_51      2635
49000_26163_26      1615
Name: count, Length: 106, dtype: int64

In [19]:
df['stratum'].value_counts()

stratum
0_0_48        839868
0_0_17        431782
0_0_39        422093
0_0_54        382043
0_0_13        367198
               ...
0_37019_37       219
0_1079_1         197
0_37141_37       169
0_53015_53        93
0_8014_8          24
Name: count, Length: 530, dtype: int64

In [20]:
# df.query("year == 2026")['cpsidp'].unique()

## Updating strata values

Ivan Strahof at IPUMS recommended that "it may make sense to restrict strata to only COUNTY and PLACEFIPS codes that appear across all vintages." Therefore, if certain strata don't appear for all year/month pairs, we'll replace their 'placefips' component with 0 in order to merge them into more general strata. If those county-statefips codes, in turn, don't appear across all strata, we'll merge them into the general statefips codes that begin with 0_0_.

### Determining which strata appear within all year/month pairs:

In [21]:
df_unique_year_month_stratum_groups = df[[
'year_and_month', 'stratum']].drop_duplicates().copy()
df_unique_year_month_stratum_groups

         year_and_month     stratum
0               2010-01    0_1003_1
3               2010-01       0_0_1
25              2010-01    0_1073_1
63              2010-01    0_1097_1
83              2010-01    0_1117_1
...                 ...         ...
23535999        2026-09    0_6089_6
23536274        2026-09  0_13113_13
23544211        2026-09    0_9001_9
23562978        2026-09  0_39109_39
23572852        2026-09    0_9015_9

[83326 rows x 2 columns]

In [22]:
df_months_with_stratum_data = df_unique_year_month_stratum_groups.pivot_table(
index = 'stratum', values = 'year_and_month', 
aggfunc = 'count').reset_index().sort_values('year_and_month', ascending = False)
df_months_with_stratum_data.rename(
columns = {'year_and_month':'year_month_pairs_with_stratum_data'}, inplace = True)
df_months_with_stratum_data.to_csv(
'Datasets/stratum_for_each_month.csv', index = False)

In [23]:
df_months_with_stratum_data['year_month_pairs_with_stratum_data'].value_counts(normalize=True)

year_month_pairs_with_stratum_data
200    0.541509
148    0.135849
67     0.115094
145    0.039623
58     0.033962
147    0.022642
13     0.022642
71     0.020755
199    0.013208
66     0.007547
198    0.005660
144    0.005660
12     0.005660
197    0.003774
143    0.003774
196    0.001887
146    0.001887
142    0.001887
141    0.001887
140    0.001887
65     0.001887
64     0.001887
62     0.001887
16     0.001887
15     0.001887
4      0.001887
3      0.001887
Name: proportion, dtype: float64

### Determining the maximum number of year-month pairs in which strata appear: 

(My new strata will all need to appear this many times, which will require consolidating quite a few of them.)

In [24]:
year_month_stratum_max = df_months_with_stratum_data[
'year_month_pairs_with_stratum_data'].max()
print(year_month_stratum_max)
df_months_with_stratum_data

200

            stratum  year_month_pairs_with_stratum_data
24           0_0_34                                 200
529     8954_6037_6                                 200
0             0_0_1                                 200
528  84000_26099_26                                 200
2            0_0_12                                 200
..              ...                                 ...
253      0_37129_37                                  12
323      0_45085_45                                  12
408        0_6101_6                                  12
414        0_8014_8                                   4
364      0_53015_53                                   3

[530 rows x 2 columns]

### Creating an initial set of revised strata:

This code checks whether a given strata appears within all year-month pairs. If it doesn't, the initial (placefips) component will be replaced with a 0, thus consolidating it into other strata that share the same county and state data, but don't have a specific placefips entry.

In [25]:
df_months_with_stratum_data['first_stratum_revision'] = np.where(
(df_months_with_stratum_data[
'year_month_pairs_with_stratum_data'] != year_month_stratum_max) & 
(df_months_with_stratum_data['stratum'].str.split('_').str[0] != '0'), 
'0_'+ (df_months_with_stratum_data['stratum'].str.split(
'_').str[1:]).str.join('_'),
df_months_with_stratum_data[
'stratum'])
         
df_months_with_stratum_data['first_stratum_revision']

24             0_0_34
529       8954_6037_6
0               0_0_1
528    84000_26099_26
2              0_0_12
            ...
253        0_37129_37
323        0_45085_45
408          0_6101_6
414          0_8014_8
364        0_53015_53
Name: first_stratum_revision, Length: 530, dtype: str

In [26]:
df_months_with_stratum_data

            stratum  year_month_pairs_with_stratum_data first_stratum_revision
24           0_0_34                                 200                 0_0_34
529     8954_6037_6                                 200            8954_6037_6
0             0_0_1                                 200                  0_0_1
528  84000_26099_26                                 200         84000_26099_26
2            0_0_12                                 200                 0_0_12
..              ...                                 ...                    ...
253      0_37129_37                                  12             0_37129_37
323      0_45085_45                                  12             0_45085_45
408        0_6101_6                                  12               0_6101_6
414        0_8014_8                                   4               0_8014_8
364      0_53015_53                                   3             0_53015_53

[530 rows x 3 columns]

## Merging these revised strata values into our list of all unique year-month/strata pairs:

In [27]:
df_unique_year_month_stratum_groups_first_revision = (
df_unique_year_month_stratum_groups.merge(df_months_with_stratum_data[
['stratum', 'first_stratum_revision']], on = 'stratum', how = 'left'))
df_unique_year_month_stratum_groups_first_revision.drop_duplicates(['year_and_month', 'first_stratum_revision'], inplace = True)
df_unique_year_month_stratum_groups_first_revision

      year_and_month     stratum first_stratum_revision
0            2010-01    0_1003_1               0_1003_1
1            2010-01       0_0_1                  0_0_1
2            2010-01    0_1073_1               0_1073_1
3            2010-01    0_1097_1               0_1097_1
4            2010-01    0_1117_1               0_1117_1
...              ...         ...                    ...
83321        2026-09    0_6089_6               0_6089_6
83322        2026-09  0_13113_13             0_13113_13
83323        2026-09    0_9001_9               0_9001_9
83324        2026-09  0_39109_39             0_39109_39
83325        2026-09    0_9015_9               0_9015_9

[79455 rows x 3 columns]

### Confirming that our np.where() code that was meant to replace 'placefips' values for strata that weren't present in all year/month pairs with 0s worked as intended:

In [28]:
df_unique_year_month_stratum_groups_first_revision.query("stratum != first_stratum_revision").drop_duplicates('first_stratum_revision').head(10)

     year_and_month         stratum first_stratum_revision
7           2010-01    37000_9003_9               0_9003_9
165         2010-01  64000_51740_51             0_51740_51
169         2010-01    73000_9001_9               0_9001_9
200         2010-01    53980_6059_6               0_6059_6
263         2010-01  53775_20091_20             0_20091_20
326         2010-01   1000_51510_51             0_51510_51
384         2010-01    69084_6085_6               0_6085_6
394         2010-01  35000_51650_51             0_51650_51
765         2010-02    80000_6037_6               0_6037_6
1193        2010-03    33000_6001_6               0_6001_6

In [29]:
### Creating a new set of year/month counts for our revised strata:

In [30]:
df_months_with_stratum_data_first_revision = df_unique_year_month_stratum_groups_first_revision.pivot_table(
index = 'first_stratum_revision', values = 'year_and_month', 
aggfunc = 'count').reset_index().sort_values('year_and_month', ascending = False)
df_months_with_stratum_data_first_revision.rename(
columns = {'year_and_month':'year_month_pairs_with_stratum_data'}, 
inplace = True)

df_months_with_stratum_data_first_revision

    first_stratum_revision  year_month_pairs_with_stratum_data
23                  0_0_33                                 200
496            8954_6037_6                                 200
0                    0_0_1                                 200
495         84000_26099_26                                 200
464          5210_53033_53                                 200
..                     ...                                 ...
326             0_45085_45                                  12
417               0_6101_6                                  12
255             0_37129_37                                  12
423               0_8014_8                                   4
371             0_53015_53                                   3

[497 rows x 2 columns]

The percentage of strata that appear within all year/month pairs has increased somewhat, but is still well below 100:

In [31]:
df_months_with_stratum_data_first_revision[
'year_month_pairs_with_stratum_data'].value_counts(normalize=True)

year_month_pairs_with_stratum_data
200    0.593561
148    0.106640
67     0.104628
145    0.042254
58     0.036217
13     0.024145
147    0.022133
71     0.022133
199    0.010060
66     0.008048
144    0.006036
12     0.006036
198    0.002012
197    0.002012
195    0.002012
65     0.002012
64     0.002012
16     0.002012
15     0.002012
4      0.002012
3      0.002012
Name: proportion, dtype: float64

### Creating a second set of revised strata: 

(For this revision, any values with non-zero county codes that don't appear in all year-month pairs will have that code replaced with a 0, thus making them identical to the 'generic' strata for their states.)

In [32]:
df_months_with_stratum_data_first_revision['second_stratum_revision'] = np.where(
(df_months_with_stratum_data_first_revision[
'year_month_pairs_with_stratum_data'] != year_month_stratum_max) & 
(df_months_with_stratum_data_first_revision['first_stratum_revision'].str.split('_').str[1] != '0'), 
df_months_with_stratum_data_first_revision['first_stratum_revision'].str.split(
'_').str[0] + '_0_' + (df_months_with_stratum_data_first_revision['first_stratum_revision'].str.split(
'_').str[2]),
df_months_with_stratum_data_first_revision[
'first_stratum_revision'])
         
df_months_with_stratum_data_first_revision

,first_stratum_revision,year_month_pairs_with_stratum_data,second_stratum_revision
23,0_0_33,200,0_0_33
496,8954_6037_6,200,8954_6037_6
0,0_0_1,200,0_0_1
495,84000_26099_26,200,84000_26099_26
464,5210_53033_53,200,5210_53033_53
...,...,...,...
326,0_45085_45,12,0_0_45
417,0_6101_6,12,0_0_6
255,0_37129_37,12,0_0_37
423,0_8014_8,4,0_0_8
371,0_53015_53,3,0_0_53

### Merging original stratum values into this dataset in order to help facilitate a merge of the second_stratum_revision field into our main DataFrame:

In [33]:
df_months_with_stratum_data_first_revision = (
df_months_with_stratum_data_first_revision.merge(
df_months_with_stratum_data.drop(
'year_month_pairs_with_stratum_data', axis = 1), 
on = 'first_stratum_revision', how = 'left'))
df_months_with_stratum_data_first_revision

,first_stratum_revision,year_month_pairs_with_stratum_data,second_stratum_revision,stratum
0,0_0_33,200,0_0_33,0_0_33
1,8954_6037_6,200,8954_6037_6,8954_6037_6
2,0_0_1,200,0_0_1,0_0_1
3,84000_26099_26,200,84000_26099_26,84000_26099_26
4,5210_53033_53,200,5210_53033_53,5210_53033_53
...,...,...,...,...
525,0_45085_45,12,0_0_45,0_45085_45
526,0_6101_6,12,0_0_6,0_6101_6
527,0_37129_37,12,0_0_37,0_37129_37
528,0_8014_8,4,0_0_8,0_8014_8
529,0_53015_53,3,0_0_53,0_53015_53

### Merging this second set of strata values into our list of unique year/month/strata pairs:

In [34]:
df_unique_year_month_stratum_groups_second_revision = (
df_unique_year_month_stratum_groups.merge(df_months_with_stratum_data_first_revision[
['stratum', 'second_stratum_revision']], on = 'stratum', how = 'left'))
df_unique_year_month_stratum_groups_second_revision

      year_and_month     stratum second_stratum_revision
0            2010-01    0_1003_1                0_1003_1
1            2010-01       0_0_1                   0_0_1
2            2010-01    0_1073_1                   0_0_1
3            2010-01    0_1097_1                0_1097_1
4            2010-01    0_1117_1                   0_0_1
...              ...         ...                     ...
83321        2026-09    0_6089_6                   0_0_6
83322        2026-09  0_13113_13                  0_0_13
83323        2026-09    0_9001_9                0_9001_9
83324        2026-09  0_39109_39                  0_0_39
83325        2026-09    0_9015_9                   0_0_9

[83326 rows x 3 columns]

In [35]:
df_unique_year_month_stratum_groups_second_revision.drop_duplicates(
['year_and_month', 'second_stratum_revision'], inplace = True)
df_unique_year_month_stratum_groups_second_revision

      year_and_month         stratum second_stratum_revision
0            2010-01        0_1003_1                0_1003_1
1            2010-01           0_0_1                   0_0_1
3            2010-01        0_1097_1                0_1097_1
5            2010-01     8000_9001_9             8000_9001_9
6            2010-01           0_0_9                   0_0_9
...              ...             ...                     ...
83314        2026-09  70000_53053_53          70000_53053_53
83315        2026-09    54652_6111_6            54652_6111_6
83319        2026-09    78582_6111_6            78582_6111_6
83320        2026-09      0_48309_48              0_48309_48
83323        2026-09        0_9001_9                0_9001_9

[59016 rows x 3 columns]

### Creating a new pivot table that checks whether all of these revised values now appear within all year/month pairs:

In [36]:
df_months_with_stratum_data_second_revision = (
df_unique_year_month_stratum_groups_second_revision.pivot_table(
index = 'second_stratum_revision', values = 'year_and_month', 
aggfunc = 'count').reset_index()).sort_values(
'year_and_month', ascending = False)
df_months_with_stratum_data_second_revision.rename(
columns = {'year_and_month':'year_month_pairs_with_stratum_data'}, 
inplace = True)

df_months_with_stratum_data_second_revision

    second_stratum_revision  year_month_pairs_with_stratum_data
295             8954_6037_6                                 200
0                     0_0_1                                 200
294          84000_26099_26                                 200
2                    0_0_12                                 200
3                    0_0_13                                 200
..                      ...                                 ...
11                   0_0_21                                 200
12                   0_0_22                                 200
13                   0_0_23                                 200
14                   0_0_24                                 200
1                    0_0_10                                  16

[296 rows x 2 columns]

Almost all of them do at this point! However, at least one statewide stratum (e.g., Deleware) doesn't appear in all year-month pairs. Therefore, in order to get all strata to appear in each sample, I'll replace all other strata for those states with their statewide strata. (I'll double-check whether this is indeed the best approach, though, since it does result in a loss of precision.)

Creating a list of states whose statewide stratum doesn't appear within all year-month pairs:

In [37]:
partial_coverage_states = (
df_months_with_stratum_data_second_revision.query(
"year_month_pairs_with_stratum_data != @year_month_stratum_max")[
'second_stratum_revision'].str.split('_').str[-1].to_list())

In [38]:
df_months_with_stratum_data_second_revision[
'final_stratum_revision'] = np.where(
df_months_with_stratum_data_second_revision[
'second_stratum_revision'].str.split('_').str[-1].isin(
partial_coverage_states),
'0_0_'+df_months_with_stratum_data_second_revision[
'second_stratum_revision'].str.split('_').str[-1], 
df_months_with_stratum_data_second_revision[
'second_stratum_revision'])

Confirming that this update was successful:

In [39]:
df_months_with_stratum_data_second_revision.query(
"final_stratum_revision.str.split('_').str[-1].isin(@partial_coverage_states)")

,second_stratum_revision,year_month_pairs_with_stratum_data,final_stratum_revision
50,0_10001_10,200,0_0_10
51,0_10003_10,200,0_0_10
52,0_10005_10,200,0_0_10
1,0_0_10,16,0_0_10

Now that we have a set of strata that appear in all months with data, we can go ahead and merge these new strata into our main DataFrame. In order to facilitate this merge, though, we'll first need to create a table of the original strata that correspond to our final strata.

In [40]:
df_months_with_stratum_data_final_revision = df_months_with_stratum_data_second_revision.merge(
df_months_with_stratum_data_first_revision.drop('year_month_pairs_with_stratum_data', axis = 1), 
on = 'second_stratum_revision', how = 'left')
df_months_with_stratum_data_final_revision

,second_stratum_revision,year_month_pairs_with_stratum_data,final_stratum_revision,first_stratum_revision,stratum
0,8954_6037_6,200,8954_6037_6,8954_6037_6,8954_6037_6
1,0_0_1,200,0_0_1,0_0_1,0_0_1
2,0_0_1,200,0_0_1,0_1081_1,0_1081_1
3,0_0_1,200,0_0_1,0_1117_1,0_1117_1
4,0_0_1,200,0_0_1,0_1073_1,0_1073_1
...,...,...,...,...,...
525,0_0_24,200,0_0_24,0_24510_24,4000_24510_24
526,0_0_24,200,0_0_24,0_24015_24,0_24015_24
527,0_0_24,200,0_0_24,0_24043_24,0_24043_24
528,0_0_24,200,0_0_24,0_24027_24,0_24027_24
529,0_0_10,16,0_0_10,0_0_10,0_0_10

Confirming that all revised strata finally have entries for every year/month pair:

In [41]:
df_final_stratum_revision_pivot = df_unique_year_month_stratum_groups.merge(
df_months_with_stratum_data_final_revision[
['stratum', 'final_stratum_revision']], on = 'stratum', how = 'left').drop_duplicates(
['year_and_month', 'final_stratum_revision']).pivot_table(
index = 'final_stratum_revision', 
values = 'year_and_month', aggfunc = 'count').reset_index()
print("Smallest year_and_month count within the dataset:", 
df_final_stratum_revision_pivot['year_and_month'].min())
df_final_stratum_revision_pivot

Smallest year_and_month count within the dataset: 200

    final_stratum_revision  year_and_month
0                    0_0_1             200
1                   0_0_10             200
2                   0_0_12             200
3                   0_0_13             200
4                   0_0_15             200
..                     ...             ...
288           78582_6111_6             200
289            8000_9001_9             200
290         82000_51810_51             200
291         84000_26099_26             200
292            8954_6037_6             200

[293 rows x 2 columns]

Merging these final data into our main DataFrame:

In [42]:
df = df.merge(df_months_with_stratum_data_final_revision[['stratum', 'final_stratum_revision']], 
on = 'stratum', how = 'left')
# df

In [43]:
df['year_and_quarter'] = df['year'].astype('str')+'-'+df['quarter']

In [44]:
df['year_and_half'] = df['year'].astype('str')+'-'+df['half']

In [45]:
df['uhrsworkt'].value_counts()

uhrsworkt
999    12479781
40      5628076
997      830340
50       690811
45       413920
         ...
188           1
161           1
172           1
174           1
196           1
Name: count, Length: 181, dtype: int64

Replacing 'hours vary' and 'not at work' uhrsworkt values with -1:

(See https://cps.ipums.org/cps-action/variables/UHRSWORKT#codes_section)

In [46]:
df['uhrsworkt_revised'] = df['uhrsworkt'].replace({999:-1, 997:-1})
df['FTE'] = np.where(df['uhrsworkt_revised'] >= 35, 1, 0)

In [47]:
df['uhrsworkt_revised'].value_counts()

uhrsworkt_revised
-1      13310121
 40      5628076
 50       690811
 45       413920
 20       375958
          ...
 188           1
 161           1
 172           1
 174           1
 196           1
Name: count, Length: 180, dtype: int64

In [48]:
df['FTE'].value_counts()

FTE
0    15121283
1     8458620
Name: count, dtype: int64

In [49]:
df['empstat'].value_counts()

empstat
10    10684061
0      4331782
36     3756196
34     2675623
32      997883
21      580469
12      416061
1        79323
22       58505
Name: count, dtype: int64

Creating a condensed version of the employment section:

(Those in the armed forces are counted as employed here.)

This code was based on the code definitions at:
https://cps.ipums.org/cps-action/variables/empstat#codes_section

In [50]:
df['empstat_condensed'] = df['empstat'].map(
{
0: 'NILF_NIU',

1: 'Employed',    
10: 'Employed',
12: 'Employed',

21: 'Unemployed',
22:'Unemployed',

32: 'NILF_NIU',
34: 'NILF_NIU',
36: 'NILF_NIU'
})

df['empstat_condensed'].value_counts()

empstat_condensed
NILF_NIU      11761484
Employed      11179445
Unemployed      638974
Name: count, dtype: int64

In [51]:
df['employed'] = np.where(df['empstat_condensed'] == 'Employed', 1, 0)

In [52]:
df['employed'].value_counts()

employed
0    12400458
1    11179445
Name: count, dtype: int64

In [53]:
df['Count'] = 1

## Creating revised weights for quarterly, half-year, and annual analyses:

In order to create accurate estimates and confidence intervals, we'll need to divide our monthly weights by the number of months within a given sample. The divisor to use will generally be 12 for years, 3 for months, and 6 for half-year estimates; however, we'll also need to account for missing (e.g. Oct 2025) and partial-year data.

For more on CPS weight adjustments, see https://forum.ipums.org/t/journalist-question-averaging-multiple-months/6058 and https://forum.ipums.org/t/how-to-count-people-in-a-specific-occupation-with-wtfinl/6742/2.

In [54]:
# Filtering out our DataFrame to include only unique year/month combinations:
# (This will prove useful for determining the number of months (i.e. samples)
# that appear within each quarter, half-year period, and year.
df_unique_years_and_months = df.drop_duplicates('year_and_month').copy().reset_index()[['year', 'year_and_month', 'year_and_quarter', 'year_and_half', 'Count']]
df_unique_years_and_months

     year year_and_month year_and_quarter year_and_half  Count
0    2010        2010-01          2010-Q1       2010-H1      1
1    2010        2010-02          2010-Q1       2010-H1      1
2    2010        2010-03          2010-Q1       2010-H1      1
3    2010        2010-04          2010-Q2       2010-H1      1
4    2010        2010-05          2010-Q2       2010-H1      1
..    ...            ...              ...           ...    ...
195  2026        2026-05          2026-Q2       2026-H1      1
196  2026        2026-06          2026-Q2       2026-H1      1
197  2026        2026-07          2026-Q3       2026-H2      1
198  2026        2026-08          2026-Q3       2026-H2      1
199  2026        2026-09          2026-Q3       2026-H2      1

[200 rows x 5 columns]

In [55]:
### Calculating the number of samples for each year, half-year, and quarter:

In [56]:
for c in ['year', 'year_and_half', 'year_and_quarter']:
    df_unique_years_and_months[f"samples_in_{c}"] = df_unique_years_and_months.groupby(c)['Count'].transform('sum')

# We could also have gotten these counts via code like the following:
df_unique_years_and_months.pivot_table(index = 'year', 
values = 'Count', aggfunc = 'sum')
    

df_unique_years_and_months

,year,year_and_month,year_and_quarter,year_and_half,Count,samples_in_year,samples_in_year_and_half,samples_in_year_and_quarter
0,2010,2010-01,2010-Q1,2010-H1,1,12,6,3
1,2010,2010-02,2010-Q1,2010-H1,1,12,6,3
2,2010,2010-03,2010-Q1,2010-H1,1,12,6,3
3,2010,2010-04,2010-Q2,2010-H1,1,12,6,3
4,2010,2010-05,2010-Q2,2010-H1,1,12,6,3
...,...,...,...,...,...,...,...,...
195,2026,2026-05,2026-Q2,2026-H1,1,9,6,3
196,2026,2026-06,2026-Q2,2026-H1,1,9,6,3
197,2026,2026-07,2026-Q3,2026-H2,1,9,3,3
198,2026,2026-08,2026-Q3,2026-H2,1,9,3,3
199,2026,2026-09,2026-Q3,2026-H2,1,9,3,3

Merging this sample-count data back into our main DataFrame so that it can be used to create alternative weights:

In [57]:
df = df.merge(df_unique_years_and_months[['year_and_month', 
'samples_in_year', 'samples_in_year_and_half', 
'samples_in_year_and_quarter']], on = 'year_and_month')

# df

### Creating revised weights for years, half-years, and quarters based on the number of monthly samples in those periods:

In [58]:
for c in ['year', 'year_and_half', 'year_and_quarter']:
    df[f"{c}_wtfinl"] = df['wtfinl'] / df[f"samples_in_{c}"]

# df

In [59]:
df['year_as_str'] = df['year'].astype('str')

In [60]:
cols_to_keep = ['age', 'year', 'occ2010', 'age_range', 'employed', 
'year_and_month', 'year_and_quarter', 'year_and_half', 'Count', 
'year_wtfinl', 'year_and_half_wtfinl', 'year_and_quarter_wtfinl', 'wtfinl', 
'year_as_str', 'empstat_condensed',
'cpsid', 'final_stratum_revision', 'age_as_int']
df_condensed = df[cols_to_keep].copy()
# df_condensed

In [61]:
## Creating a Polars-based copy of this dataset for use within
# subsequent analyses:

dfp_condensed = pl.DataFrame(df_condensed)
dfp_condensed

shape: (23_579_903, 18)
┌─────┬──────┬──────────────┬─────────────┬───┬─────────────┬───────────┬─────────────┬────────────┐
│ age ┆ year ┆ occ2010      ┆ age_range   ┆ … ┆ empstat_con ┆ cpsid     ┆ final_strat ┆ age_as_int │
│ --- ┆ ---  ┆ ---          ┆ ---         ┆   ┆ densed      ┆ ---       ┆ um_revision ┆ ---        │
│ i8  ┆ i16  ┆ str          ┆ str         ┆   ┆ ---         ┆ f64       ┆ ---         ┆ i64        │
│     ┆      ┆              ┆             ┆   ┆ str         ┆           ┆ str         ┆            │
╞═════╪══════╪══════════════╪═════════════╪═══╪═════════════╪═══════════╪═════════════╪════════════╡
│ 60  ┆ 2010 ┆ Medical and  ┆ 60 or older ┆ … ┆ Employed    ┆ 2.0091e13 ┆ 0_1003_1    ┆ 60         │
│     ┆      ┆ health       ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ services ma… ┆             ┆   ┆             ┆           ┆             ┆            │
│ 29  ┆ 2010 ┆ Miscellaneou ┆ 25-29       ┆ … ┆ Unemployed  ┆ 2.0091e13 ┆ 0_1003_1    ┆ 29         │
│     ┆      ┆ s            ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ agricultural ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ wor…         ┆             ┆   ┆             ┆           ┆             ┆            │
│ 85  ┆ 2010 ┆ niu          ┆ 60 or older ┆ … ┆ NILF_NIU    ┆ 2.0081e13 ┆ 0_1003_1    ┆ 85         │
│ 52  ┆ 2010 ┆ Diagnostic   ┆ 50-54       ┆ … ┆ Unemployed  ┆ 2.0081e13 ┆ 0_0_1       ┆ 52         │
│     ┆      ┆ related      ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ technologis… ┆             ┆   ┆             ┆           ┆             ┆            │
│ 37  ┆ 2010 ┆ Electricians ┆ 35-39       ┆ … ┆ Unemployed  ┆ 2.0081e13 ┆ 0_0_1       ┆ 37         │
│ …   ┆ …    ┆ …            ┆ …           ┆ … ┆ …           ┆ …         ┆ …           ┆ …          │
│ 28  ┆ 2026 ┆ Automotive   ┆ 25-29       ┆ … ┆ Employed    ┆ 2.0251e13 ┆ 0_0_39      ┆ 28         │
│     ┆      ┆ glass        ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ installers   ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ an…          ┆             ┆   ┆             ┆           ┆             ┆            │
│ 25  ┆ 2026 ┆ Office       ┆ 25-29       ┆ … ┆ Employed    ┆ 2.0251e13 ┆ 0_0_39      ┆ 25         │
│     ┆      ┆ clerks,      ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ general      ┆             ┆   ┆             ┆           ┆             ┆            │
│ 51  ┆ 2026 ┆ niu          ┆ 50-54       ┆ … ┆ NILF_NIU    ┆ 2.0261e13 ┆ 0_0_19      ┆ 51         │
│ 50  ┆ 2026 ┆ Customer     ┆ 50-54       ┆ … ┆ Employed    ┆ 2.0261e13 ┆ 0_0_19      ┆ 50         │
│     ┆      ┆ service repr ┆             ┆   ┆             ┆           ┆             ┆            │
│     ┆      ┆ esentativ…   ┆             ┆   ┆             ┆           ┆             ┆            │
│ 16  ┆ 2026 ┆ Retail       ┆ 21 or       ┆ … ┆ Employed    ┆ 2.0261e13 ┆ 0_0_19      ┆ 16         │
│     ┆      ┆ salespersons ┆ younger     ┆   ┆             ┆           ┆             ┆            │
└─────┴──────┴──────────────┴─────────────┴───┴─────────────┴───────────┴─────────────┴────────────┘

In [62]:
unique_years = list(df['year'].unique())
unique_years

[np.int16(2010),
 np.int16(2011),
 np.int16(2012),
 np.int16(2013),
 np.int16(2014),
 np.int16(2015),
 np.int16(2016),
 np.int16(2017),
 np.int16(2018),
 np.int16(2019),
 np.int16(2020),
 np.int16(2021),
 np.int16(2022),
 np.int16(2023),
 np.int16(2024),
 np.int16(2025),
 np.int16(2026)]

## Creating estimates for each period, both for all ages together and by age range

**To do: Update the following script so that, if an entry for the given year is already present in Datasets, the loop will import that CSV file, then add it to df_list_Full. (If it's not present, the loop will then generate new stats.) This will prevent you from having to uncessarily process the same data over and over again for older years whenever you get new monthly data for the current year. (You'd just need to delete the current year's data, though, or add it to a 'years_to_redo' list that could be incorporated into your `if` statement.)**

## Debugging RAM issues by testing out individual total and proportion calculations:

In [63]:
latest_year_and_month = df['year_and_month'].max()
latest_year_and_month

'2026-09'

Checking estimated employment numbers for the most recent year and month:

In [64]:
df

,year,serial,month,hwtfinl,cpsid,asecflag,statefip,county,individcc,placefips,faminc,pernum,wtfinl,cpsidp,cpsidv,age,empstat,occ,occ2010_code,occ1990,occ1950,ind,uhrsworkt,whyunemp,occ2010,age_as_int,age_range,quarter,half,year_and_month,stratum,final_stratum_revision,year_and_quarter,year_and_half,uhrsworkt_revised,FTE,empstat_condensed,employed,Count,samples_in_year,samples_in_year_and_half,samples_in_year_and_quarter,year_wtfinl,year_and_half_wtfinl,year_and_quarter_wtfinl,year_as_str
0,2010,1,1,3565.7334,2.009120e+13,NaN,1,1003,0,0,820,1,3565.7334,2.009120e+13,2.009120e+14,60,10,350,350,15,290,8190,40,0,Medical and health services managers,60,60 or older,Q1,H1,2010-01,0_1003_1,0_1003_1,2010-Q1,2010-H1,40,1,Employed,1,1,12,6,3,297.144450,594.288900,1188.577800,2010
1,2010,1,1,3565.7334,2.009120e+13,NaN,1,1003,0,0,820,2,2802.2961,2.009120e+13,2.009120e+14,29,21,6050,6050,479,820,170,999,1,"Miscellaneous agricultural workers, including ...",29,25-29,Q1,H1,2010-01,0_1003_1,0_1003_1,2010-Q1,2010-H1,-1,0,Unemployed,0,1,12,6,3,233.524675,467.049350,934.098700,2010
2,2010,6,1,3200.7455,2.008121e+13,NaN,1,1003,0,0,740,1,3200.7455,2.008121e+13,2.008121e+14,85,36,0,9999,999,999,0,999,0,niu,85,60 or older,Q1,H1,2010-01,0_1003_1,0_1003_1,2010-Q1,2010-H1,-1,0,NILF_NIU,0,1,12,6,3,266.728792,533.457583,1066.915167,2010
3,2010,7,1,3453.5073,2.008100e+13,NaN,1,0,0,0,740,1,3453.5073,2.008100e+13,2.008100e+14,52,21,3320,3320,206,94,7580,999,3,Diagnostic related technologists and technicians,52,50-54,Q1,H1,2010-01,0_0_1,0_0_1,2010-Q1,2010-H1,-1,0,Unemployed,0,1,12,6,3,287.792275,575.584550,1151.169100,2010
4,2010,7,1,3453.5073,2.008100e+13,NaN,1,0,0,0,740,2,3270.5279,2.008100e+13,2.008100e+14,37,21,6350,6355,575,515,770,999,3,Electricians,37,35-39,Q1,H1,2010-01,0_0_1,0_0_1,2010-Q1,2010-H1,-1,0,Unemployed,0,1,12,6,3,272.543992,545.087983,1090.175967,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23579898,2026,42551,9,4688.6175,2.025080e+13,NaN,39,0,0,0,842,3,5335.4792,2.025080e+13,2.025080e+14,28,10,7160,7160,514,550,3570,40,0,Automotive glass installers and repairers,28,25-29,Q3,H2,2026-09,0_0_39,0_0_39,2026-Q3,2026-H2,40,1,Employed,1,1,9,3,3,592.831022,1778.493067,1778.493067,2026
23579899,2026,42551,9,4688.6175,2.025080e+13,NaN,39,0,0,0,842,4,5100.8981,2.025080e+13,2.025080e+14,25,10,5860,5860,379,390,6570,40,0,"Office clerks, general",25,25-29,Q3,H2,2026-09,0_0_39,0_0_39,2026-Q3,2026-H2,40,1,Employed,1,1,9,3,3,566.766456,1700.299367,1700.299367,2026
23579900,2026,42552,9,2524.5904,2.026070e+13,NaN,19,0,0,0,820,1,3327.3207,2.026070e+13,2.026070e+14,51,36,0,9999,999,999,0,999,0,niu,51,50-54,Q3,H2,2026-09,0_0_19,0_0_19,2026-Q3,2026-H2,-1,0,NILF_NIU,0,1,9,3,3,369.702300,1109.106900,1109.106900,2026
23579901,2026,42552,9,2524.5904,2.026070e+13,NaN,19,0,0,0,820,2,2524.5904,2.026070e+13,2.026070e+14,50,10,5240,5240,376,390,8191,40,0,Customer service representatives,50,50-54,Q3,H2,2026-09,0_0_19,0_0_19,2026-Q3,2026-H2,40,1,Employed,1,1,9,3,3,280.510044,841.530133,841.530133,2026
23579902,2026,42552,9,2524.5904,2.026070e+13,NaN,19,0,0,0,820,3,2353.8331,2.026070e+13,2.026070e+14,16,10,4760,4760,275,490,5371,8,0,Retail salespersons,16,21 or younger,Q3,H2,2026-09,0_0_19,0_0_19,2026-Q3,2026-H2,8,0,Employed,1,1,9,3,3,261.537011,784.611033,784.611033,2026

In [65]:
df_latest_occupational_employment = df.query(
"year_and_month == @latest_year_and_month & occ2010 != 'niu'").pivot_table(
index = 'occ2010', values = 'wtfinl', aggfunc = 'sum').sort_values(
'wtfinl', ascending = False).reset_index()
df_latest_occupational_employment

                                               occ2010        wtfinl
0    Miscellaneous managers, including funeral serv...  7.529658e+06
1                                    Registered nurses  3.895131e+06
2               Driver/sales workers and truck drivers  3.890115e+06
3                Elementary and middle school teachers  3.784311e+06
4       First-line supervisors of retail sales workers  2.975726e+06
..                                                 ...           ...
448  Textile winding, twisting, and drawing out mac...  4.990881e+03
449                    Forest and conservation workers  4.765288e+03
450                              Etchers and engravers  2.461148e+03
451                                New accounts clerks  1.743872e+03
452                                 Procurement clerks  1.241456e+03

[453 rows x 2 columns]

Creating a list of occupations with at least 1 million workers: (This list will also get incorporated into our HTML file. Note that it may change slightly each month as new data becomes available.)

In [66]:
large_occupations = df_latest_occupational_employment.query(
"wtfinl >= 1000000")['occ2010'].to_list().copy()
large_occupations.sort()
large_occupations

['Accountants and auditors',
 'Bookkeeping, accounting, and auditing clerks',
 'Carpenters',
 'Cashiers',
 'Chief executives and legislators',
 'Childcare workers',
 'Combined food preparation and serving workers, including fast food',
 'Computer occupations, all other',
 'Construction laborers',
 'Construction managers',
 'Cooks',
 'Counselors',
 'Couriers and messengers',
 'Customer service representatives',
 'Driver/sales workers and truck drivers',
 'Electricians',
 'Elementary and middle school teachers',
 'Financial managers',
 'First-line supervisors of non-retail sales workers',
 'First-line supervisors of office and administrative support workers',
 'First-line supervisors of retail sales workers',
 'Food preparation workers',
 'Food service managers',
 'General and operations managers',
 'Grounds maintenance workers',
 'Janitors and building cleaners',
 'Laborers and freight, stock, and material movers, hand',
 'Lawyers, and judges, magistrates, and other judicial workers',
 'Maids and housekeeping cleaners',
 'Management analysts',
 'Marketing and sales managers',
 'Miscellaneous agricultural workers, including animal breeders',
 'Miscellaneous managers, including funeral service managers and postmasters and mail superintendents',
 'Miscellaneous production workers, including semiconductor processors',
 'Nursing, psychiatric, and home health aides',
 'Office clerks, general',
 'Other teachers and instructors',
 'Personal care aides',
 'Physicians and surgeons',
 'Real estate brokers and sales agents',
 'Receptionists and information clerks',
 'Registered nurses',
 'Retail salespersons',
 'Sales representatives, wholesale and manufacturing',
 'Secretaries and administrative assistants',
 'Software developers, applications and systems software',
 'Stock clerks and order fillers',
 'Teacher assistants',
 'Waiters and waitresses']

In [67]:
period_entry_files = os.listdir(svy_period_entry_file_folder)
period_entry_files[0:5]

[]

In [68]:
# Specifying the weight value to use for each period:
period_weight_map = {'year_as_str':"year_wtfinl",
                     'year_and_half':"year_and_half_wtfinl",
                     'year_and_quarter':"year_and_quarter_wtfinl",
                     'year_and_month':"wtfinl"}

## Testing out perform_svy_analysis() function:

In [69]:
period = 'year_and_month'
period_entry = '2026-08'
df_query_string = 'year_and_month == @period_entry'
y = 'Count'

Specifying the design for the survey: (This is based on Ivan Stranhof's guidance and on the svy documentation at https://svylab.com/docs/svy/tutorials/estimation.html.)

In [70]:
design = svy.Design(wgt=period_weight_map[period],
stratum = 'final_stratum_revision', psu = 'cpsid',
singleton = 'center')

# Note RE singleton handling:
# I went with the 'center' method, 
# because according to the documentation for R's 'survey' 
# library, the corresponding 'survey' method for treating 
# lonely PSUs (adjust) is conservative.

Creating a simpler design merely for testing purposes:

In [71]:
# simpler_design = svy.Design(wgt=period_weight_map[period])

In [72]:
frac_val = 1 # The % of responses that will be included in the
# test sample. (Smaller values will result in faster, but less accurate,
# calculations.)
period_entry_sample = svy.Sample(data=pl.DataFrame(
df_condensed.query(df_query_string).sample(frac=frac_val)), 
design=design)

In [73]:
sample_filter = [svy.col("occ2010") != "niu", svy.col(
"employed") == 1, svy.col('occ2010').isin(large_occupations)]

In [74]:
comparison_list = ['occ2010', 'age_range']
by_list = [period] + comparison_list.copy()
by_list_overall = [period, 'occ2010']
by_list, by_list_overall

(['year_and_month', 'occ2010', 'age_range'], ['year_and_month', 'occ2010'])

In [75]:
period_entry_sample.data.group_by('employed').len()

shape: (2, 2)
┌──────────┬───────┐
│ employed ┆ len   │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 48067 │
│ 1        ┆ 43988 │
└──────────┴───────┘

In [76]:
period_entry_sample.wrangling.filter_records(
        sample_filter).data.to_pandas()[y].count()

np.int64(23185)

In [77]:
sample_filter

[Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841ED6D0>),
 Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841ED220>),
 Expr(<Expr ['col("occ2010").is_in([["Accoun…'] at 0x7AE3841EDB80>)]

In [78]:
# df_svy_result = perform_svy_analysis(
#     sample = period_entry_sample, y = 'Count', 
#     analysis_type = 'total', by = by_list_overall, where = sample_filter, 
#     col_suffix = '')
# df_svy_result

In [79]:
df_svy_result = perform_svy_analysis(
    sample = period_entry_sample, y = 'Count', 
    analysis_type = 'total', by = by_list_overall, 
    #where = sample_filter, 
    col_suffix = '', return_as_pandas = True)
df_svy_result

,year_and_month,occ2010,est,se,lci,uci,cv,df,n,error_upper,error_lower
0,2026-08,Accountants and auditors,1.881612e+06,103218.507102,1.678511e+06,2.084712e+06,0.054856,309,469,203100.051254,203100.051254
1,2026-08,Actors,5.786494e+04,17281.114016,2.868721e+03,1.128612e+05,0.298646,3,12,54996.217450,54996.217450
2,2026-08,Actuaries,6.353400e+03,6353.399900,NaN,NaN,1.000000,0,1,NaN,NaN
3,2026-08,Adhesive bonding machine operators and tenders,1.020962e+04,7446.788852,NaN,NaN,0.729390,0,2,NaN,NaN
4,2026-08,Administrative services managers,2.222173e+05,32696.743437,1.525259e+05,2.919088e+05,0.147139,15,63,69691.458940,69691.458940
...,...,...,...,...,...,...,...,...,...,...,...
449,2026-08,"Weighers, measurers, checkers, and samplers, r...",9.870696e+04,22183.097484,4.625227e+04,1.511617e+05,0.224737,7,26,52454.690287,52454.690287
450,2026-08,"Welding, soldering, and brazing workers",5.184617e+05,51811.484307,4.153536e+05,6.215698e+05,0.099933,80,145,103108.139720,103108.139720
451,2026-08,"Wholesale and retail buyers, except farm products",1.220972e+05,24435.517040,6.230568e+04,1.818888e+05,0.200132,6,35,59791.556235,59791.556235
452,2026-08,Word processors and typists,2.945557e+04,12073.523060,NaN,NaN,0.409889,0,7,NaN,NaN
453,2026-08,Writers and authors,2.994963e+05,40402.098946,2.169842e+05,3.820084e+05,0.134900,30,80,82512.093855,82512.093855

In [80]:
# period_entry_sample.singleton.summary()

In [81]:
prop_sample_filter = [

    svy.col('empstat_condensed').isin(['Employed', 'Unemployed']),
    svy.col('occ2010').isin(large_occupations)
]

prop_sample_filter

[Expr(<Expr ['col("empstat_condensed").is_in…'] at 0x7AE29C19A300>),
 Expr(<Expr ['col("occ2010").is_in([["Accoun…'] at 0x7AE29C19A120>)]

In [82]:
period_entry_sample.wrangling.filter_records(
prop_sample_filter).data.to_pandas().pivot_table(
index = ['year_and_half', 'occ2010', 'empstat_condensed'], 
values = 'Count',
aggfunc = 'count').reset_index()

,year_and_half,occ2010,empstat_condensed,Count
0,2026-H2,Accountants and auditors,Employed,455
1,2026-H2,Accountants and auditors,Unemployed,9
2,2026-H2,"Bookkeeping, accounting, and auditing clerks",Employed,369
3,2026-H2,"Bookkeeping, accounting, and auditing clerks",Unemployed,2
4,2026-H2,Carpenters,Employed,274
...,...,...,...,...
93,2026-H2,Stock clerks and order fillers,Unemployed,41
94,2026-H2,Teacher assistants,Employed,318
95,2026-H2,Teacher assistants,Unemployed,33
96,2026-H2,Waiters and waitresses,Employed,428
97,2026-H2,Waiters and waitresses,Unemployed,17

In [83]:
prop_sample_filter

[Expr(<Expr ['col("empstat_condensed").is_in…'] at 0x7AE29C19A300>),
 Expr(<Expr ['col("occ2010").is_in([["Accoun…'] at 0x7AE29C19A120>)]

In [84]:
by_list_overall

['year_and_month', 'occ2010']

In [85]:
df_svy_result = perform_svy_analysis(
    sample = period_entry_sample, y = 'empstat_condensed', 
    analysis_type = 'prop', by = by_list_overall, where = prop_sample_filter, 
    col_suffix = '_emp_prop', return_as_pandas = True)
df_svy_result

,year_and_month,occ2010,empstat_condensed_emp_prop,est_emp_prop,se_emp_prop,lci_emp_prop,uci_emp_prop,cv_emp_prop,df_emp_prop,n_emp_prop,error_upper_emp_prop,error_lower_emp_prop,est_as_pct_emp_prop,se_as_pct_emp_prop,lci_as_pct_emp_prop,uci_as_pct_emp_prop,error_upper_as_pct_emp_prop,error_lower_as_pct_emp_prop,prop_val_n_emp_prop
0,2026-08,Accountants and auditors,Employed,0.978986,0.007212,0.958967,0.989346,0.007367,304,464,0.010361,0.020018,97.898566,0.721190,95.896730,98.934629,1.036063,2.001836,455
1,2026-08,Accountants and auditors,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,304,464,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0
2,2026-08,Accountants and auditors,Unemployed,0.021014,0.007212,0.010654,0.041033,0.343190,304,464,0.020018,0.010361,2.101434,0.721190,1.065371,4.103270,2.001836,1.036063,9
3,2026-08,"Bookkeeping, accounting, and auditing clerks",Employed,0.987936,0.008587,0.951957,0.997054,0.008691,248,371,0.009118,0.035979,98.793605,0.858661,95.195670,99.705406,0.911800,3.597935,369
4,2026-08,"Bookkeeping, accounting, and auditing clerks",NILF_NIU,0.000000,0.000000,NaN,NaN,inf,248,371,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,2026-08,Teacher assistants,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,212,351,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0
143,2026-08,Teacher assistants,Unemployed,0.103976,0.018899,0.072179,0.147551,0.181764,212,351,0.043575,0.031796,10.397561,1.889898,7.217941,14.755108,4.357547,3.179621,33
144,2026-08,Waiters and waitresses,Employed,0.959917,0.010874,0.932116,0.976618,0.011328,287,445,0.016701,0.027801,95.991656,1.087356,93.211558,97.661770,1.670114,2.780098,428
145,2026-08,Waiters and waitresses,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,287,445,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0
146,2026-08,Waiters and waitresses,Unemployed,0.040083,0.010874,0.023382,0.067884,0.271273,287,445,0.027801,0.016701,4.008344,1.087356,2.338230,6.788442,2.780098,1.670114,17

In [86]:
# df_svy_result.query("empstat_condensed_emp_prop == 'Unemployed'")

## Creating both overall estimates and estimates by age range for various periods:

In order to prevent my computer from running out of RAM, I ended up performing individual analyses for each period entry (e.g. 2025, 2023-01, 2024-Q3), then saving each one to a .csv file. All of these .csv files will then get combined into a single .csv file shortly.

In [87]:
if run_svy_analyses == True:
    for y, analysis_type in [
        ['Count', 'total'], ['empstat_condensed', 'prop']]:
        if y == 'Count':
            # I decided to remove column suffixes for now,
            # since I'm not yet merging total-employment
            # and unemployment data together--which means these
            # suffixes won't be necessary.
            col_suffix = '' #''
        elif y == 'empstat_condensed':
            col_suffix = ''#'_ue_prop'
        else:
            raise ValueError("Unrecognized comparison-type value!")
        for comparison_type in ['job', 'job_by_age_range']:
            
            for period in ['year_as_str', 'year_and_half', 'year_and_quarter', 
        'year_and_month']:
                # Determining all of the period entries within this sample:
                # (To reduce our RAM usage, we'll perform individual analyses for each
                # period entry.)
                unique_periods = df[period].unique().copy()
                for period_entry in unique_periods:
                    df_query_string = f"{period} == @period_entry"
                    # Specifying which comparison variables to use for 
                    # our table of sums:
                    if comparison_type == 'job':
                        comparison_list = ['occ2010']
                        
                        # The default sample-filter argument will be used
                        # for our total-employment analyses. In this case,
                        # we'll want to filter out non-employed respondents
                        # and those who don't have an occupation listed.
                        sample_filter = [svy.col("occ2010") != "niu", 
                            svy.col("employed") == 1]
                        # Replacing this default argument with a custom one
                        # for our unemployment-proportion analyses:
                        # (Here, we do want to include both employed and
                        # unemployed respondents (but not those out of the
                        # labor force. We'll still want to remove
                        # 'niu' occupation values, though.)
                        if analysis_type == 'prop':
                            sample_filter = [svy.col("occ2010") != "niu", 
                            svy.col('empstat_condensed').isin(
                            ['Employed', 'Unemployed'])]
                    elif comparison_type == 'job_by_age_range':
                        comparison_list = ['occ2010', 'age_range']
                        # Because age-range-based data will have wider
                        # confidence intervals (and will consume more 
                        # memory), we'll limit our analyses to those
                        # occupations in our large_occupations list.
                        # Since 'niu' isn't in our large-occupations list,
                        # we don't have to filter for that variable in this
                        # case.
                        # Default filter for employment-total calculations:
                        sample_filter = [svy.col("employed") == 1, 
                            svy.col('occ2010').isin(large_occupations)]
                        # Changing the filter value for unemployment-%
                        # calculations:
                        if analysis_type == 'prop':
                            sample_filter = [
                            svy.col('empstat_condensed').isin(
                            ['Employed', 'Unemployed']),
                            svy.col('occ2010').isin(large_occupations)]
                    else:
                        raise ValueError(
                        "Unrecognized comparison-type value!")
                
                            
                    result_key = (y+'_'+analysis_type+'_'+comparison_type 
                    + '_for_' + period + '_' + period_entry)
                    filename = f'{result_key}.csv'
                    
                    by_list = [period] + comparison_list.copy()
            
            # To avoid out-of-memory errors (which I encountered even with 64 GB
            # of RAM plus a 70-GB swapfile), I'll perform analyses for one period 
            # entry (e.g. one year, one quarter of one year, etc.)
            # at a time. I don't believe that this will affect the accuracy of 
            # our confidence-interval calculations, as the CPS's weights were
            # originally calculated at the monthly level.           
    
    
                    # Determining whether a new analysis needs to be 
                    # run for the active loop components:
                    
                    if filename in period_entry_files:
                        filename_contains_redo_substring = False
                        # Seeing whether a substring within a list of 
                        # filename substrings to redo is present within
                        # this filename: (If so, an analysis will still be
                        # run, and the existing file will get overwritten.)
                        for redo_substring in filename_substrings_to_redo:
                            if redo_substring in filename:
                                filename_contains_redo_substring = True
                                break
                        if filename_contains_redo_substring == False:
                            print(f"{filename} already present in folder. \
Skipping this analysis.")
                            continue

                    # Creating a sample design object for the active year
                    # and period type:
                    # (This code was based on the quickstart example at 
                    # https://svylab.com/docs/svy/#quick-start .)
            
                    # I would normally have made a copy of the DataFrame
                    # earlier in the loop in order to reduce the number of 
                    # query operations, but this approach should help
                    # save RAM while also preventing the original DataFrame
                    # from getting unintentionally modified.
            
                    # NOTE: It's important to only filter the DataFrame
                    # by the year at this point, as we'll need data for
                    # all respondents for each year (including those without
                    # jobs) in order to calculate accurate confidence intervals.

                    # Also note that I'm using the center() method, as
                    # discussed earlier, to deal with any lonely PSUs
                    # that may be present.

                    # Interestingly, specifying PSUs and strata
                    # appeared to speed up the analysis somewhat--perhaps
                    # because it allowed svy to perform calculations
                    # in smaller chunks? (For instance, per-year calculations
                    # initially took around 3 minutes, but now they
                    # take closer to 1 minute.)
                    
                    period_entry_sample = svy.Sample(data=pl.DataFrame(
                    df_condensed.query(df_query_string).copy()), 
                    # You could probably exclude the .copy() call here
                    # if needed if doing so would save RAM.
                    design=svy.Design(stratum='final_stratum_revision', psu='cpsid', 
                    wgt=period_weight_map[period], singleton = 'center'))
            
                    # When debugging this script, it can be helpful to add
                    # .sample(frac=0.001) to the output of .query(), 
                    # as doing so will
                    # dramatically reduce the time needed for the loop to
                    # finish running.
                    
                    # Passing additional filters to the sample *here*
                    # (within the estimation.total() call), rather than
                    # the previous query() call,
                    # will allow us to calculate proportions for our population
                    # of interest without distorting confidence intervals.

                    print("result_key:", result_key, "by_list:",
                    by_list, "sample_filter:", sample_filter,
                    "df_query_string:", df_query_string)
                    
                    analysis_start_time = time.time()
                    # Performing our svy analysis:
                    # This will be either a total- or proportions-type
                    # estimate.
                    df_results_period_entry = perform_svy_analysis(
                        sample = period_entry_sample, y = y, 
                        analysis_type = analysis_type, by = by_list, where = sample_filter, 
                        col_suffix = col_suffix, return_as_pandas = True)
                    analysis_end_time = time.time()
                    print(f"Finished svy function in {round(
                    analysis_end_time - analysis_start_time, 3)} seconds.")
                    
                    # It's important to note that not everyone with an
                    # occ2010 entry is actually employed, as this value
                    # can also represent the last occupation in which someone
                    # worked before becoming unemployed.
                    # Also note that, in order to obtain accurate confidence
                    # intervals, the dataset being fed to estimation.total
                    # should include all CPS rows for a given year rather than
                    # just those who are employed. 
                    # See https://cps.ipums.org/cps-action/variables/OCC#description_section
                    # For more on OCC2010, see:
                    # https://cps.ipums.org/cps-action/variables/OCC2010#description_section
            
                    # Freeing up memory by deleting period_entry_sample
                    # and running a garbage collector:
                    # (Based on
                    # https://www.geeksforgeeks.org/python/how-to-explicitly-free-memory-in-python/
                    # )
                    # (Ended up removing this because it didn't solve
                    # the RAM-depletion issues I was facing)
                    # del period_entry_sample
                    # gc.collect()
                    
                    # Using standardized 'period' and 'period_val'
                    # fields will make it easier to concatenate
                    # tables for various results.
                    df_results_period_entry['period'] = period
                    df_results_period_entry.rename(
                    columns = {period:'period_val'}, inplace = True)
                    if comparison_type == 'job':
                        df_results_period_entry['age_range'] = 'All'
                        
                    print("Length of DataFrame:", len(df_results_period_entry), 
                    "\n")    
                    
                    df_results_period_entry.to_csv(svy_period_entry_file_folder+'/'+filename, index = False)

result_key: Count_total_job_for_year_as_str_2010 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE29C19B3E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE29C19B2F0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 29.397 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_as_str_2011 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F4025E50>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F4025F40>)] df_query_string: year_as_str == @period_entry
Finished svy function in 33.886 seconds.
Length of DataFrame: 474

result_key: Count_total_job_for_year_as_str_2012 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F40274D0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F40276B0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 31.742 seconds.
Length of DataFrame: 474

result_key: Count_total_job_for_year_as_str_2013 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1A6E2EC60>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1A6E2EA80>)] df_query_string: year_as_str == @period_entry
Finished svy function in 32.986 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2014 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1A6E2E5D0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1A6E2E7B0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 35.274 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2015 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1DE0159A0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1DE0154F0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 32.431 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2016 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFB1FA7F20>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFD4500050>)] df_query_string: year_as_str == @period_entry
Finished svy function in 31.705 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2017 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EFC50>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EFA70>)] df_query_string: year_as_str == @period_entry
Finished svy function in 29.651 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2018 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1A3678AA0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1A3678410>)] df_query_string: year_as_str == @period_entry
Finished svy function in 27.662 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2019 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE058027200>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE058026C60>)] df_query_string: year_as_str == @period_entry
Finished svy function in 28.275 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_as_str_2020 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EE120>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EE300>)] df_query_string: year_as_str == @period_entry
Finished svy function in 27.335 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2021 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D7FE30>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D7FC50>)] df_query_string: year_as_str == @period_entry
Finished svy function in 24.171 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2022 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D7F980>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D7F890>)] df_query_string: year_as_str == @period_entry
Finished svy function in 22.72 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2023 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F51D6B70>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F51D68A0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 22.226 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2024 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1AEC5D400>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1AEC5D4F0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 23.199 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2025 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D7F890>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D7C5F0>)] df_query_string: year_as_str == @period_entry
Finished svy function in 20.714 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_as_str_2026 by_list: ['year_as_str', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE42F6A80>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE42F6D50>)] df_query_string: year_as_str == @period_entry
Finished svy function in 15.425 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2010-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADEE7FEB200>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADEE7FEB890>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.343 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_half_2010-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D7F4D0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D7EF30>)] df_query_string: year_and_half == @period_entry
Finished svy function in 14.246 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_half_2011-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F75A37A0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F75A36B0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.005 seconds.
Length of DataFrame: 474

result_key: Count_total_job_for_year_and_half_2011-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1E414FC50>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1E414FA70>)] df_query_string: year_and_half == @period_entry
Finished svy function in 14.935 seconds.
Length of DataFrame: 474

result_key: Count_total_job_for_year_and_half_2012-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EFE30>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EFF20>)] df_query_string: year_and_half == @period_entry
Finished svy function in 16.255 seconds.
Length of DataFrame: 474

result_key: Count_total_job_for_year_and_half_2012-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFAB38BE30>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFAB38B980>)] df_query_string: year_and_half == @period_entry
Finished svy function in 16.134 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2013-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D1BF20>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D1BE30>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.706 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2013-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F6B11E50>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F6B13980>)] df_query_string: year_and_half == @period_entry
Finished svy function in 16.169 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2014-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1AB27AC60>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1AB27A5D0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.912 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2014-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1DE00DB80>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1DE00E3F0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 16.431 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2015-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1DE00F980>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1DE00F6B0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.877 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2015-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE01B3675C0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE01B366D50>)] df_query_string: year_and_half == @period_entry
Finished svy function in 14.851 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2016-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D47980>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D473E0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.964 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2016-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7D47D40>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7D476B0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.447 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2017-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F410E8A0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F410F110>)] df_query_string: year_and_half == @period_entry
Finished svy function in 16.364 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2017-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1AB2528A0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1AB252210>)] df_query_string: year_and_half == @period_entry
Finished svy function in 15.283 seconds.
Length of DataFrame: 471

result_key: Count_total_job_for_year_and_half_2018-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1AB2533E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1AB253A70>)] df_query_string: year_and_half == @period_entry
Finished svy function in 13.693 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2018-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F6B4F2F0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F6B4EE40>)] df_query_string: year_and_half == @period_entry
Finished svy function in 14.656 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2019-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1D40E9B80>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1D40E96D0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 14.635 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2019-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EF110>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EE990>)] df_query_string: year_and_half == @period_entry
Finished svy function in 13.277 seconds.
Length of DataFrame: 472

result_key: Count_total_job_for_year_and_half_2020-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1D41673E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1D41675C0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.17 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2020-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE0500FDB80>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE0500FDA90>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.358 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2021-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1AEC6FE30>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1AEC6FF20>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.41 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2021-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EF980>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EF6B0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 12.226 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2022-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1EF579F40>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1EF5798B0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.06 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2022-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE01B3D1310>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE01B3D07D0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 10.787 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2023-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841ED7C0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841ED9A0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.935 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2023-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE0587A9400>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE0587AA030>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.082 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2024-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADEE7F227B0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADEE7F225D0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.353 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2024-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F41C2030>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F41C1A90>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.694 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2025-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE3841EE300>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE3841EF020>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.299 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2025-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F7519040>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F7519310>)] df_query_string: year_and_half == @period_entry
Finished svy function in 9.923 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2026-H1 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1D40373E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1D4036A80>)] df_query_string: year_and_half == @period_entry
Finished svy function in 11.433 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_half_2026-H2 by_list: ['year_and_half', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE29C19BF20>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE29C19B5C0>)] df_query_string: year_and_half == @period_entry
Finished svy function in 5.551 seconds.
Length of DataFrame: 456

result_key: Count_total_job_for_year_and_quarter_2010-Q1 by_list: ['year_and_quarter', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F5BD64E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F5BD6300>)] df_query_string: year_and_quarter == @period_entry
Finished svy function in 8.074 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_quarter_2010-Q2 by_list: ['year_and_quarter', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE058753A70>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE058753890>)] df_query_string: year_and_quarter == @period_entry
Finished svy function in 7.618 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_quarter_2010-Q3 by_list: ['year_and_quarter', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFAB3758B0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFAB3759A0>)] df_query_string: year_and_quarter == @period_entry
Finished svy function in 8.631 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_quarter_2010-Q4 by_list: ['year_and_quarter', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE01B125400>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE01B125310>)] df_query_string: year_and_quarter == @period_entry
Finished svy function in 8.836 seconds.
Length of DataFrame: 450

result_key: Count_total_job_for_year_and_quarter_2011-Q1 by_list: ['year_and_quarter', 'occ2010'] sample_filter: [Expr(<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7AE1F65024E0>), Expr(<Expr ['[(col("employed")) == (dyn int…'] at 0x7AE1F6502210>)] df_query_string: year_and_quarter == @period_entry
Finished svy function in 8.735 seconds.
Length of DataFrame: 474


## Creating Polars-based analyses for data-checking purposes:

These analyses will run more quickly but won't contain valuable confidence-interval data that we'll want to incorporate into the dashboard.

In [88]:
period = 'year_as_str'
comparison_list = ['occ2010']
by_list = [period] + comparison_list
weight_col = period_weight_map[period]
query_string = "occ2010 != 'niu' & employed == 1"
ones_col = 'Count'
col_suffix = '_emp_total_pd'
analysis_method = 'Total'
dv = ''
# Total-employment pivot:

# df_pivot = pd.pivot_table(df_condensed.query(query_string), 
# index=by_list, values = [weight_col, count_col], aggfunc = 'sum').reset_index()
# df_pivot.rename(columns = {count_col:'Response_Count',weight_col:'Total'}, inplace = True)
# if col_suffix != '':
#     col_renaming_dict = {c:c+col_suffix if c not in by_list else c 
#     for c in df_pivot.columns}
#     df_pivot.rename(columns = col_renaming_dict, inplace = True)

survey_pivot(df = df_condensed.query(query_string), 
weight_col = weight_col, analysis_method = analysis_method, 
by_list = by_list, dv = dv, col_suffix = col_suffix, ones_col = ones_col)

,year_as_str,occ2010,n_emp_total_pd,Total_emp_total_pd
0,2010,Accountants and auditors,8820,1.648526e+06
1,2010,Actors,124,2.494031e+04
2,2010,Actuaries,135,2.524293e+04
3,2010,Adhesive bonding machine operators and tenders,50,9.736348e+03
4,2010,Administrative services managers,615,1.044482e+05
...,...,...,...,...
7889,2026,"Welding, soldering, and brazing workers",1432,5.662952e+05
7890,2026,"Wholesale and retail buyers, except farm products",299,1.313709e+05
7891,2026,"Woodworking machine setters, operators, and te...",30,1.245637e+04
7892,2026,Word processors and typists,62,2.455136e+04
7893,2026,Writers and authors,562,2.178417e+05

In [89]:
weight_col = period_weight_map[period]
df_test = pl_survey_pivot(dfp_condensed.filter(
[pl.col("occ2010") != 'niu', pl.col("employed") == 1]), 
weight_col = weight_col, analysis_method = 'Total',
                    by_list = [period] + comparison_list, dv = '', col_suffix = '',
                    add_suffix_to_dv = False,
                    convert_output_to_pandas = False)
df_test

shape: (7_894, 4)
┌─────────────┬─────────────────────────────────┬───────────────┬───────┐
│ year_as_str ┆ occ2010                         ┆ Total         ┆ Count │
│ ---         ┆ ---                             ┆ ---           ┆ ---   │
│ str         ┆ str                             ┆ f64           ┆ u32   │
╞═════════════╪═════════════════════════════════╪═══════════════╪═══════╡
│ 2010        ┆ Accountants and auditors        ┆ 1.6485e6      ┆ 8820  │
│ 2010        ┆ Actors                          ┆ 24940.308708  ┆ 124   │
│ 2010        ┆ Actuaries                       ┆ 25242.925742  ┆ 135   │
│ 2010        ┆ Adhesive bonding machine opera… ┆ 9736.347858   ┆ 50    │
│ 2010        ┆ Administrative services manage… ┆ 104448.199833 ┆ 615   │
│ …           ┆ …                               ┆ …             ┆ …     │
│ 2026        ┆ Welding, soldering, and brazin… ┆ 566295.201789 ┆ 1432  │
│ 2026        ┆ Wholesale and retail buyers, e… ┆ 131370.886911 ┆ 299   │
│ 2026        ┆ Woodworking machine setters, o… ┆ 12456.369644  ┆ 30    │
│ 2026        ┆ Word processors and typists     ┆ 24551.361078  ┆ 62    │
│ 2026        ┆ Writers and authors             ┆ 217841.698122 ┆ 562   │
└─────────────┴─────────────────────────────────┴───────────────┴───────┘

In [90]:
# Unemployment-proportion pivot:
period = 'year_as_str'
dv = 'empstat_condensed'
comparison_list = ['occ2010']
by_list = [period, 'age_range']#[period] + comparison_list
weight_col = period_weight_map[period]
query_string = "occ2010 != 'niu' & empstat_condensed in ['Employed', 'Unemployed']"
ones_col = 'Count'
col_suffix = '_ue_prop_pd'
analysis_method = 'Proportion'
comparison_type = 'job_by_age_range'

# df_pivot = pd.pivot_table(df_condensed.query(query_string), 
# index=by_list + [dv], values = [weight_col, count_col], aggfunc = 'sum').reset_index()
# df_pivot.rename(columns = {count_col:'Response_Count',weight_col:'Total'}, inplace = True)
# # Calculating proportions by dividing the 'Total' column for each row
# # by the sum of all 'Total' values for each set of by_list values:
# df_pivot['dv_prop'] = df_pivot['Total'] / df_pivot.groupby(
# by_list)['Total'].transform('sum')
# if col_suffix != '':
#     col_renaming_dict = {c:c+col_suffix if c not in by_list else c 
#     for c in df_pivot.columns}
#     df_pivot.rename(columns = col_renaming_dict, inplace = True)
                
df_results_for_period = survey_pivot(df = df_condensed.query(query_string), 
weight_col = weight_col, analysis_method = analysis_method, 
by_list = by_list, dv = dv, col_suffix = col_suffix, ones_col = ones_col)

df_results_for_period['period'] = period
df_results_for_period.rename(
columns = {period:'period_val'}, inplace = True)
if comparison_type == 'job':
    df_results_for_period['age_range'] = 'All'

df_results_for_period

,period_val,age_range,empstat_condensed_ue_prop_pd,n_ue_prop_pd,Total_ue_prop_pd,Proportion_ue_prop_pd,period
0,2010,21 or younger,Employed,49215,9.267662e+06,0.851228,year_as_str
1,2010,21 or younger,Unemployed,8083,1.619735e+06,0.148772,year_as_str
2,2010,22-24,Employed,39743,8.205933e+06,0.869508,year_as_str
3,2010,22-24,Unemployed,5566,1.231508e+06,0.130492,year_as_str
4,2010,25-29,Employed,77059,1.537788e+07,0.894338,year_as_str
...,...,...,...,...,...,...,...
335,2026,50-54,Unemployed,1084,4.654352e+05,0.029756,year_as_str
336,2026,55-59,Employed,37059,1.442474e+07,0.970844,year_as_str
337,2026,55-59,Unemployed,1037,4.332005e+05,0.029156,year_as_str
338,2026,60 or older,Employed,67589,2.380205e+07,0.969359,year_as_str
339,2026,60 or older,Unemployed,2010,7.523612e+05,0.030641,year_as_str

In [91]:
# Unemployment-proportion pivot:
period = 'year_as_str'
dv = 'empstat_condensed'
comparison_list = ['occ2010']
by_list = [period, 'age_range']#[period] + comparison_list
weight_col = period_weight_map[period]
col_suffix = '_ue_prop_pd'
analysis_method = 'Proportion'
comparison_type = 'job_by_age_range'

df_results_for_period = pl_survey_pivot(dfp = dfp_condensed.filter(
[pl.col("occ2010") != 'niu', pl.col(
"empstat_condensed").is_in(['Employed', 'Unemployed'])]),
weight_col = weight_col, analysis_method = analysis_method, 
by_list = by_list, dv = dv)
df_results_for_period

shape: (340, 7)
┌─────────────┬───────────────┬──────────────────┬───────────────┬───────┬────────────┬────────────┐
│ year_as_str ┆ age_range     ┆ empstat_condense ┆ Total         ┆ Count ┆ Proportion ┆ Percentage │
│ ---         ┆ ---           ┆ d                ┆ ---           ┆ ---   ┆ ---        ┆ ---        │
│ str         ┆ str           ┆ ---              ┆ f64           ┆ u32   ┆ f64        ┆ f64        │
│             ┆               ┆ str              ┆               ┆       ┆            ┆            │
╞═════════════╪═══════════════╪══════════════════╪═══════════════╪═══════╪════════════╪════════════╡
│ 2010        ┆ 21 or younger ┆ Employed         ┆ 9.2677e6      ┆ 49215 ┆ 0.851228   ┆ 85.122844  │
│ 2010        ┆ 21 or younger ┆ Unemployed       ┆ 1.6197e6      ┆ 8083  ┆ 0.148772   ┆ 14.877156  │
│ 2010        ┆ 22-24         ┆ Employed         ┆ 8.2059e6      ┆ 39743 ┆ 0.869508   ┆ 86.950829  │
│ 2010        ┆ 22-24         ┆ Unemployed       ┆ 1.2315e6      ┆ 5566  ┆ 0.130492   ┆ 13.049171  │
│ 2010        ┆ 25-29         ┆ Employed         ┆ 1.5378e7      ┆ 77059 ┆ 0.894338   ┆ 89.43381   │
│ …           ┆ …             ┆ …                ┆ …             ┆ …     ┆ …          ┆ …          │
│ 2026        ┆ 50-54         ┆ Unemployed       ┆ 465435.197356 ┆ 1084  ┆ 0.029756   ┆ 2.975633   │
│ 2026        ┆ 55-59         ┆ Employed         ┆ 1.4425e7      ┆ 37059 ┆ 0.970844   ┆ 97.084385  │
│ 2026        ┆ 55-59         ┆ Unemployed       ┆ 433200.5185   ┆ 1037  ┆ 0.029156   ┆ 2.915615   │
│ 2026        ┆ 60 or older   ┆ Employed         ┆ 2.3802e7      ┆ 67589 ┆ 0.969359   ┆ 96.935942  │
│ 2026        ┆ 60 or older   ┆ Unemployed       ┆ 752361.239211 ┆ 2010  ┆ 0.030641   ┆ 3.064058   │
└─────────────┴───────────────┴──────────────────┴───────────────┴───────┴────────────┴────────────┘

In [92]:
if run_polars_analyses == True:
    for analysis_type in ['total_employment', 'unemployment_proportion']:
        if analysis_type == 'total_employment':
            col_suffix = ''#'_emp_total_pd' # The 'pd' addition (which stands
            # for Pandas) will distinguish these columns from their
            # svy-based equivalents, which will prove useful when merging
            # svy- and Pandas-based analyses together.
            analysis_method = 'Total'
            dv = ''
        elif analysis_type == 'unemployment_proportion':
            col_suffix = '' #'_ue_prop_pd'
            analysis_method = 'Proportion'
            dv = 'empstat_condensed'
        for comparison_type in ['job', 'job_by_age_range']:
            for period in ['year_as_str', 'year_and_half', 'year_and_quarter', 
        'year_and_month']:
                weight_col = period_weight_map[period]
                
                if comparison_type == 'job':
                    comparison_list = ['occ2010']
                    # Query string for total-employment calculations:
                    filter_entry = [pl.col("occ2010") != 'niu',  pl.col("employed") == 1]
                    
                    if analysis_method == 'Proportion':
                        # Changing the query string for unemployment-%
                        # calculations:
                        filter_entry = [pl.col("occ2010") != 'niu', 
            pl.col("empstat_condensed").is_in(['Employed', 'Unemployed'])]
                        
                elif comparison_type == 'job_by_age_range':
                    comparison_list = ['occ2010', 'age_range']
                    # Query string for total-employment calculations:
                    filter_entry = [pl.col("employed") == 1, pl.col(
                    "occ2010").is_in(large_occupations)]
                    
                    if analysis_method == 'Proportion':
                        # Changing the query string for unemployment-%
                        # calculations:
                        filter_entry = [pl.col(
"empstat_condensed").is_in(['Employed', 'Unemployed']), 
pl.col("occ2010").is_in(large_occupations)]
                        
                else:
                    raise ValueError(
                    "Unrecognized comparison-type value!")
            
                result_key = (analysis_type+'_'+comparison_type 
                + '_for_' + period)
                filename = f'{result_key}_pandas.csv'
                
                by_list = [period] + comparison_list.copy()
        
                print("result_key:", result_key, "by_list:",
                by_list, "filter_entry:", filter_entry, "weight_col",
                weight_col)
    
                analysis_start_time = time.time()
                # Performing our svy analysis:
                # This will be either a total- or proportions-type
                # estimate.
                df_results_for_period = pl_survey_pivot(
                    dfp = dfp_condensed.filter(filter_entry), 
                    weight_col = weight_col, 
                    analysis_method = analysis_method, 
                    by_list = by_list, dv = dv,
                    col_suffix = col_suffix,
                    convert_output_to_pandas=True)
                analysis_end_time = time.time()
                print(f"Finished Pandas-based survey_pivot() \
function in {round(analysis_end_time - analysis_start_time, 3)} seconds.")
                
                df_results_for_period['period'] = period
                df_results_for_period.rename(
                columns = {period:'period_val'}, inplace = True)
                if comparison_type == 'job':
                    df_results_for_period['age_range'] = 'All'
                    
                print("Length of DataFrame:", len(df_results_for_period), 
                "\n")    
                
                df_results_for_period.to_csv(
                polars_analyses_file_folder+'/'+filename, index = False)

result_key: total_employment_job_for_year_as_str by_list: ['year_as_str', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD27B0>, <Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD26C0>] weight_col year_wtfinl
Finished Pandas-based survey_pivot() function in 0.643 seconds.
Length of DataFrame: 7894

result_key: total_employment_job_for_year_and_half by_list: ['year_and_half', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD2990>, <Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD28A0>] weight_col year_and_half_wtfinl
Finished Pandas-based survey_pivot() function in 0.609 seconds.
Length of DataFrame: 15785

result_key: total_employment_job_for_year_and_quarter by_list: ['year_and_quarter', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD26C0>, <Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD27B0>] weight_col year_and_quarter_wtfinl
Finished Pandas-based survey_pivot() function in 0.671 seconds.
Length of DataFrame: 31099

result_key: total_employment_job_for_year_and_month by_list: ['year_and_month', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD28A0>, <Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD2990>] weight_col wtfinl
Finished Pandas-based survey_pivot() function in 0.634 seconds.
Length of DataFrame: 92634

result_key: total_employment_job_by_age_range_for_year_as_str by_list: ['year_as_str', 'occ2010', 'age_range'] filter_entry: [<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD26C0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD27B0>] weight_col year_wtfinl
Finished Pandas-based survey_pivot() function in 0.422 seconds.
Length of DataFrame: 8313

result_key: total_employment_job_by_age_range_for_year_and_half by_list: ['year_and_half', 'occ2010', 'age_range'] filter_entry: [<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD2990>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD28A0>] weight_col year_and_half_wtfinl
Finished Pandas-based survey_pivot() function in 0.413 seconds.
Length of DataFrame: 16602

result_key: total_employment_job_by_age_range_for_year_and_quarter by_list: ['year_and_quarter', 'occ2010', 'age_range'] filter_entry: [<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD27B0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD26C0>] weight_col year_and_quarter_wtfinl
Finished Pandas-based survey_pivot() function in 0.413 seconds.
Length of DataFrame: 32667

result_key: total_employment_job_by_age_range_for_year_and_month by_list: ['year_and_month', 'occ2010', 'age_range'] filter_entry: [<Expr ['[(col("employed")) == (dyn int…'] at 0x7ADFE2DD28A0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD2990>] weight_col wtfinl
Finished Pandas-based survey_pivot() function in 0.454 seconds.
Length of DataFrame: 97139

result_key: unemployment_proportion_job_for_year_as_str by_list: ['year_as_str', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD28A0>, <Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD2990>] weight_col year_wtfinl
Finished Pandas-based survey_pivot() function in 0.733 seconds.
Length of DataFrame: 15321

result_key: unemployment_proportion_job_for_year_and_half by_list: ['year_and_half', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD28A0>, <Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD2990>] weight_col year_and_half_wtfinl
Finished Pandas-based survey_pivot() function in 0.689 seconds.
Length of DataFrame: 29751

result_key: unemployment_proportion_job_for_year_and_quarter by_list: ['year_and_quarter', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD28A0>, <Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD2990>] weight_col year_and_quarter_wtfinl
Finished Pandas-based survey_pivot() function in 0.728 seconds.
Length of DataFrame: 56242

result_key: unemployment_proportion_job_for_year_and_month by_list: ['year_and_month', 'occ2010'] filter_entry: [<Expr ['[(col("occ2010")) != ("niu")]'] at 0x7ADFE2DD28A0>, <Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD2990>] weight_col wtfinl
Finished Pandas-based survey_pivot() function in 0.826 seconds.
Length of DataFrame: 155183

result_key: unemployment_proportion_job_by_age_range_for_year_as_str by_list: ['year_as_str', 'occ2010', 'age_range'] filter_entry: [<Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD28A0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD2990>] weight_col year_wtfinl
Finished Pandas-based survey_pivot() function in 0.471 seconds.
Length of DataFrame: 16414

result_key: unemployment_proportion_job_by_age_range_for_year_and_half by_list: ['year_and_half', 'occ2010', 'age_range'] filter_entry: [<Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD28A0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD2990>] weight_col year_and_half_wtfinl
Finished Pandas-based survey_pivot() function in 0.512 seconds.
Length of DataFrame: 32358

result_key: unemployment_proportion_job_by_age_range_for_year_and_quarter by_list: ['year_and_quarter', 'occ2010', 'age_range'] filter_entry: [<Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD28A0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD2990>] weight_col year_and_quarter_wtfinl
Finished Pandas-based survey_pivot() function in 0.523 seconds.
Length of DataFrame: 62069

result_key: unemployment_proportion_job_by_age_range_for_year_and_month by_list: ['year_and_month', 'occ2010', 'age_range'] filter_entry: [<Expr ['col("empstat_condensed").is_in…'] at 0x7ADFE2DD28A0>, <Expr ['col("occ2010").is_in([["Accoun…'] at 0x7ADFE2DD2990>] weight_col wtfinl
Finished Pandas-based survey_pivot() function in 0.582 seconds.
Length of DataFrame: 172364

## Combining files created within the previous cells into new DataFrames:

## To do: consider updating the following code so that unemployment proportions are merged horizontally into the employment-totals table. (period, period_val, occ2010, and age_range should make for good merge keys.) 

(You could also remove the unique suffixes from both tables, then add a new table that clarifies what the values represent--but having the items side by side should work fine. Alternatively, you could keep these two datasets separate if the combined copy would be too large to upload to GitHub.)

In [93]:
# df_pl = pd.read_csv('/home/kjb3/D1V1/kjb3docs/Programming/\
# py/kjb3_programs_2/employment_trends/svy_period_entry_\
# datasets/empstat_condensed_prop_job_by_age_range_for_year_and_month_2026-01.csv')
# df_pl

In [94]:
df_pl = pd.read_csv('/home/kjb3/D1V1/kjb3docs/Programming/\
py/kjb3_programs_2/employment_trends/svy_period_entry_\
datasets/Count_total_job_by_age_range_for_year_and_month_2026-06.csv')
df_pl

,period_val,occ2010,age_range,est,se,lci,uci,cv,df,n,error_upper,error_lower,period
0,2026-06,Accountants and auditors,21 or younger,14263.6469,8601.093973,NaN,NaN,0.603008,0,4,NaN,NaN,year_and_month
1,2026-06,Accountants and auditors,22-24,50661.8979,16344.857727,NaN,NaN,0.322626,0,12,NaN,NaN,year_and_month
2,2026-06,Accountants and auditors,25-29,289482.5051,46194.260273,180250.436975,398714.573225,0.159575,7,54,109232.068125,109232.068125,year_and_month
3,2026-06,Accountants and auditors,30-34,192698.3381,32204.882982,122529.925881,262866.750319,0.167126,12,51,70168.412219,70168.412219,year_and_month
4,2026-06,Accountants and auditors,35-39,252173.6598,37812.978660,172013.725960,332333.593640,0.149948,16,59,80159.933840,80159.933840,year_and_month
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,2026-06,Waiters and waitresses,40-44,116929.0088,24423.566273,39202.320551,194655.697049,0.208875,3,31,77726.688249,77726.688249,year_and_month
481,2026-06,Waiters and waitresses,45-49,39811.3109,13236.129067,-128369.654937,207992.276737,0.332472,1,12,168180.965837,168180.965837,year_and_month
482,2026-06,Waiters and waitresses,50-54,66154.2543,18815.224685,6275.812019,126032.696581,0.284414,3,16,59878.442281,59878.442281,year_and_month
483,2026-06,Waiters and waitresses,55-59,27000.9110,10735.038207,NaN,NaN,0.397581,0,8,NaN,NaN,year_and_month
484,2026-06,Waiters and waitresses,60 or older,62309.4248,15716.771089,18672.672642,105946.176958,0.252237,4,25,43636.752158,43636.752158,year_and_month

In [95]:
df_pl

,period_val,occ2010,age_range,est,se,lci,uci,cv,df,n,error_upper,error_lower,period
0,2026-06,Accountants and auditors,21 or younger,14263.6469,8601.093973,NaN,NaN,0.603008,0,4,NaN,NaN,year_and_month
1,2026-06,Accountants and auditors,22-24,50661.8979,16344.857727,NaN,NaN,0.322626,0,12,NaN,NaN,year_and_month
2,2026-06,Accountants and auditors,25-29,289482.5051,46194.260273,180250.436975,398714.573225,0.159575,7,54,109232.068125,109232.068125,year_and_month
3,2026-06,Accountants and auditors,30-34,192698.3381,32204.882982,122529.925881,262866.750319,0.167126,12,51,70168.412219,70168.412219,year_and_month
4,2026-06,Accountants and auditors,35-39,252173.6598,37812.978660,172013.725960,332333.593640,0.149948,16,59,80159.933840,80159.933840,year_and_month
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,2026-06,Waiters and waitresses,40-44,116929.0088,24423.566273,39202.320551,194655.697049,0.208875,3,31,77726.688249,77726.688249,year_and_month
481,2026-06,Waiters and waitresses,45-49,39811.3109,13236.129067,-128369.654937,207992.276737,0.332472,1,12,168180.965837,168180.965837,year_and_month
482,2026-06,Waiters and waitresses,50-54,66154.2543,18815.224685,6275.812019,126032.696581,0.284414,3,16,59878.442281,59878.442281,year_and_month
483,2026-06,Waiters and waitresses,55-59,27000.9110,10735.038207,NaN,NaN,0.397581,0,8,NaN,NaN,year_and_month
484,2026-06,Waiters and waitresses,60 or older,62309.4248,15716.771089,18672.672642,105946.176958,0.252237,4,25,43636.752158,43636.752158,year_and_month

In [98]:
# df_period = pd.read_csv(
# '/home/kjb3/D1V1/kjb3docs/Programming/py/kjb3_programs_2/\
# employment_trends/svy_period_entry_datasets/Count_total_job_by_age_\
# range_for_year_and_half_2012-H1.csv')
# df_period.rename(columns = {c:c.replace('', '') for c in df_period.columns},
#                 inplace = True)
# df_period.rename(columns = {'Response_Count':'n'}, inplace = True)
# df_period

In [99]:
# Importing all individual datasets created usisng the previous cell,
# together with any pre-existing datasets, into a single DataFrame:

# df_full_emp_totals = pd.concat([pd.read_csv(
# svy_period_entry_file_folder+'/'+filename) for 
# filename in os.listdir(svy_period_entry_file_folder)
# if ('Count_total' in filename)])

# Temporary approach that applies necessary renaming operations
# prior to concatenating DataFrames:
# (Once you regenerate older DataFrames, this approach won't be
# necessary, and you can use the previous, commented-out line 
# instead)

df_full_emp_totals_list = []
for filename in os.listdir(svy_period_entry_file_folder):
    if 'Count_total' in filename:
        df_period = pd.read_csv(
        svy_period_entry_file_folder+'/'+filename)
        df_period.rename(
        columns = {c:c.replace('_emp_total', '') for c in df_period.columns},
        inplace = True)
        if 'n' in df_period.columns:
            df_period.rename(
                columns = {'Response_Count':'prop_val_n'}, 
            inplace = True)
        else:
            df_period.rename(
                columns = {'Response_Count':'n'}, inplace = True)
    
        df_full_emp_totals_list.append(df_period)

df_full_emp_totals = pd.concat(
    [df for df in df_full_emp_totals_list])

# This code is a temporary fix--and should be safely removed
# once all employment calculations are rerun.
df_full_emp_totals['age_range'] = df_full_emp_totals['age_range'].replace(
{'Under 22':'21 or younger'})


df_full_emp_totals.sort_values(['period', 'period_val', 
'occ2010', 'age_range'], inplace = True)

# I hadn't included error-bar fields within all of my 
# total-employment .csv files, so I'll add in any such missing
# calculations here.
df_full_emp_totals['error_upper'] = df_full_emp_totals[
'uci'] - df_full_emp_totals['est']
df_full_emp_totals['error_lower'] = df_full_emp_totals[
'est'] - df_full_emp_totals['lci']

df_full_emp_totals.to_csv('Datasets/full_emp_totals.csv', index = False)

In [100]:
df_full_emp_totals['age_range'].value_counts()

age_range
All              147412
25-29             15563
30-34             15563
40-44             15563
55-59             15563
60 or older       15563
35-39             15562
45-49             15562
50-54             15561
22-24             15294
21 or younger     14927
Name: count, dtype: int64

In [101]:
df_full_emp_totals['age_range'].value_counts()

age_range
All              147412
25-29             15563
30-34             15563
40-44             15563
55-59             15563
60 or older       15563
35-39             15562
45-49             15562
50-54             15561
22-24             15294
21 or younger     14927
Name: count, dtype: int64

In [102]:
df_full_emp_totals

,period_val,occ2010,est,se,lci,uci,cv,df,n,error_upper,error_lower,period,age_range
0,2010-H1,Accountants and auditors,8077.425633,2315.385111,NaN,NaN,0.286649,0,24,NaN,NaN,year_and_half,21 or younger
1,2010-H1,Accountants and auditors,93416.485450,12113.519936,68742.052785,118090.918115,0.129672,32,216,24674.432665,24674.432665,year_and_half,22-24
2,2010-H1,Accountants and auditors,234778.698733,18694.350464,197832.200429,271725.197038,0.079625,146,566,36946.498305,36946.498305,year_and_half,25-29
3,2010-H1,Accountants and auditors,203440.958083,17644.757265,168493.293036,238388.623130,0.086732,116,555,34947.665047,34947.665047,year_and_half,30-34
4,2010-H1,Accountants and auditors,229360.245217,18394.196838,192996.178280,265724.312153,0.080198,141,579,36364.066936,36364.066936,year_and_half,35-39
...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,2026,"Welding, soldering, and brazing workers",566295.201789,30797.384985,505779.240398,626811.163180,0.054384,475,1432,60515.961391,60515.961391,year_as_str,All
452,2026,"Wholesale and retail buyers, except farm products",131370.886911,14218.888023,102898.054776,159843.719046,0.108235,57,299,28472.832135,28472.832135,year_as_str,All
453,2026,"Woodworking machine setters, operators, and te...",12456.369644,3818.896062,3111.867611,21800.871678,0.306582,6,30,9344.502033,9344.502033,year_as_str,All
454,2026,Word processors and typists,24551.361078,5437.810245,-44542.569212,93645.291367,0.221487,1,62,69093.930289,69093.930289,year_as_str,All
455,2026,Writers and authors,217841.698122,18871.598486,180553.206072,255130.190173,0.086630,150,562,37288.492051,37288.492051,year_as_str,All

## Modifying this dataset for use within our HTML site:

Converting population totals to integers not only makes the output more readable, but also reduces the size of the data file that we're about to create.

In [103]:
# Trimming out columns that won't be need for the dashboard should help
# our page load faster.
# NOTE: If you'll need to keep unemployment %s and employment totals separate in order to save space, you can create
# two separate cols-for-dashboard lists, one for each type, and then use those to more efficiently save your data to .txt/.csv files.
cols_for_dashboard = ['period', 'period_val', 'occ2010', 'est', 
'lci', 'uci', 'age_range', 
'n']

In [104]:
df_full_emp_totals_for_site = df_full_emp_totals[cols_for_dashboard].copy()

for c in ['est', 'lci', 'uci']:
    df_full_emp_totals_for_site[c] = df_full_emp_totals_for_site[
    c].round(0).astype('Int64')
    # Casting to an Int64 in order to accommodate NaN values
df_full_emp_totals_for_site

,period,period_val,occ2010,est,lci,uci,age_range,n
0,year_and_half,2010-H1,Accountants and auditors,8077,<NA>,<NA>,21 or younger,24
1,year_and_half,2010-H1,Accountants and auditors,93416,68742,118091,22-24,216
2,year_and_half,2010-H1,Accountants and auditors,234779,197832,271725,25-29,566
3,year_and_half,2010-H1,Accountants and auditors,203441,168493,238389,30-34,555
4,year_and_half,2010-H1,Accountants and auditors,229360,192996,265724,35-39,579
...,...,...,...,...,...,...,...,...
451,year_as_str,2026,"Welding, soldering, and brazing workers",566295,505779,626811,All,1432
452,year_as_str,2026,"Wholesale and retail buyers, except farm products",131371,102898,159844,All,299
453,year_as_str,2026,"Woodworking machine setters, operators, and te...",12456,3112,21801,All,30
454,year_as_str,2026,Word processors and typists,24551,-44543,93645,All,62
455,year_as_str,2026,Writers and authors,217842,180553,255130,All,562

In [105]:
df_full_emp_totals_for_site.to_csv(
'Datasets/svy_emp_totals.csv', index = False)

Updating the csv_data.js file that will get used as a data source by the dashboard:

(To create the file, we'll simply add some JavaScript code to the front and end of a CSV render of df_full_emp_totals_for_site. This will be more efficient than manually copying and pasting the CSV data into our JavaScript file.)

In [106]:
csv_data_js_string = "let csv_data = `" + df_full_emp_totals_for_site.to_csv(
index=False) + "`;\nvar df_unfiltered = d3.csvParse(csv_data);"

In [107]:
with open ('csv_data.js', 'w') as file:
    file.write(csv_data_js_string)

## Creating option elements that can then get incorporated within our HTML page:

In [108]:
unique_age_ranges = list(df_full_emp_totals_for_site['age_range'].unique()).copy()
unique_age_ranges.remove('All')
unique_age_ranges.sort()
unique_age_ranges

['21 or younger',
 '22-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60 or older']

In [109]:
unique_occupations = [occ for occ in df_full_emp_totals_for_site[
'occ2010'].unique()].copy()
unique_occupations.sort()

Creating a string of JavaScript that will include occupation options in HTML format: (Large occupations will be flagged with an 'L' to make them easier to identify.)

In [110]:
all_occupations_string = "var full_occupation_options = `"

for occupation in unique_occupations:
    if occupation in large_occupations:
        large_occupation_prefix = "(L) "
    else:
        large_occupation_prefix = ""
#     print(f'<option value="{occupation}">{large_occupation_prefix}\
# {occupation}</option>')
    occupation_option_string =  f'<option value="{occupation}">{
large_occupation_prefix}{occupation}</option>\n'
    all_occupations_string += occupation_option_string

all_occupations_string += "`;\n\n" # The multiple line breaks will make
# it easier to distinguish between separate variables in our JavaScript
# file.

Creating a similar list for larger occupations:

In [111]:
large_occupations_string = "var large_occupation_options = `"
for occupation in large_occupations:
    large_occupations_string += f'<option value="{occupation}">(L) {occupation}</option>\n'

large_occupations_string += "`;\n\n"

In [112]:
large_occupations_array = "var large_occupations = " + str(large_occupations) + ";"

Combining these different variables into a single string:

In [113]:
occ_option_info_string = all_occupations_string + large_occupations_string + large_occupations_array

In [114]:
with open('occ_option_info.js', 'w') as file:
    file.write(occ_option_info_string)

# Specifying a discrete colorscale that can be used within JavaScript:

In [115]:
px.colors.qualitative.Dark24

['#2E91E5',
 '#E15F99',
 '#1CA71C',
 '#FB0D0D',
 '#DA16FF',
 '#222A2A',
 '#B68100',
 '#750D86',
 '#EB663B',
 '#511CFB',
 '#00A08B',
 '#FB00D1',
 '#FC0080',
 '#B2828D',
 '#6C7C32',
 '#778AAE',
 '#862A16',
 '#A777F1',
 '#620042',
 '#1616A7',
 '#DA60CA',
 '#6C4516',
 '#0D2A63',
 '#AF0038']

## Importing Pandas totals:

In [116]:
df_pl_emp_totals = pd.concat([pd.read_csv(
polars_analyses_file_folder+'/'+filename) for 
filename in os.listdir(polars_analyses_file_folder) if (
'total_employment' in filename)])

df_pl_emp_totals

,period_val,occ2010,Total,Count,period,age_range
0,2010,Accountants and auditors,1.648526e+06,8820,year_as_str,All
1,2010,Actors,2.494031e+04,124,year_as_str,All
2,2010,Actuaries,2.524293e+04,135,year_as_str,All
3,2010,Adhesive bonding machine operators and tenders,9.736348e+03,50,year_as_str,All
4,2010,Administrative services managers,1.044482e+05,615,year_as_str,All
...,...,...,...,...,...,...
97134,2026-09,Waiters and waitresses,9.707047e+04,28,year_and_month,40-44
97135,2026-09,Waiters and waitresses,7.482815e+04,18,year_and_month,45-49
97136,2026-09,Waiters and waitresses,6.823808e+04,13,year_and_month,50-54
97137,2026-09,Waiters and waitresses,4.729730e+04,12,year_and_month,55-59
97138,2026-09,Waiters and waitresses,7.517555e+04,23,year_and_month,60 or older

In [117]:
df_condensed['employed_as_software_developer'] = np.where(
(df_condensed['occ2010'] == 'Software developers, applications \
and systems software') & (df_condensed['employed'] == 1), 1, 0)

#df

In [118]:
df_pl_emp_totals.to_csv(
'Datasets/pl_emp_totals.csv', index = False)

In [119]:
df_syv_pd_emp_comparison = df_full_emp_totals.merge(
df_pl_emp_totals, on = ['period', 'period_val', 'occ2010', 'age_range'], 
how = 'outer') # An outer merge will allow us to identify rows that
# are present in only one of the two datasets

df_syv_pd_emp_comparison['svy_pd_emp_total_diff'] = abs(
df_syv_pd_emp_comparison['est'] - df_syv_pd_emp_comparison['Total'])

df_syv_pd_emp_comparison.head()

,period_val,occ2010,est,se,lci,uci,cv,df,n,error_upper,error_lower,period,age_range,Total,Count,svy_pd_emp_total_diff
0,2010-H1,Accountants and auditors,8077.425633,2315.385111,NaN,NaN,0.286649,0,24,NaN,NaN,year_and_half,21 or younger,8077.425633,24,9.094947e-13
1,2010-H1,Accountants and auditors,93416.485450,12113.519936,68742.052785,118090.918115,0.129672,32,216,24674.432665,24674.432665,year_and_half,22-24,93416.485450,216,7.275958e-11
2,2010-H1,Accountants and auditors,234778.698733,18694.350464,197832.200429,271725.197038,0.079625,146,566,36946.498305,36946.498305,year_and_half,25-29,234778.698733,566,0.000000e+00
3,2010-H1,Accountants and auditors,203440.958083,17644.757265,168493.293036,238388.623130,0.086732,116,555,34947.665047,34947.665047,year_and_half,30-34,203440.958083,555,2.910383e-11
4,2010-H1,Accountants and auditors,229360.245217,18394.196838,192996.178280,265724.312153,0.080198,141,579,36364.066936,36364.066936,year_and_half,35-39,229360.245217,579,1.164153e-10

Determining the maximum difference in estimates between these two datasets: (This value will most likely be greater than 0 due to minor rounding differences, or if one dataset is missing data for a certain time period.)

In [120]:
df_syv_pd_emp_comparison['svy_pd_emp_total_diff'].max()

np.float64(8.009374141693115e-08)

## Checking unemployment data:

**Note:** Due to low sample sizes, the ACS may be a better source of occupation-specific unemployment estimates than the CPS (though its data isn't as recent).

In [121]:
df_ue_props = pd.concat([pd.read_csv(
svy_period_entry_file_folder+'/'+filename, dtype={'period_val':'str'}) for 
filename in os.listdir(svy_period_entry_file_folder) if (
'prop_job' in filename)]).sort_values('period_val').reset_index(drop=True)

df_ue_props_list = []

for filename in os.listdir(svy_period_entry_file_folder):
    if 'prop_job' in filename:
        df_period = pd.read_csv(
        svy_period_entry_file_folder+'/'+filename)
        df_period.rename(
        columns = {c:c.replace('_ue_prop', '') for c in df_period.columns},
        inplace = True)
        df_period.rename(
            columns = {'Response_Count':'prop_val_n'}, 
            inplace = True)

        df_ue_props_list.append(df_period)

df_ue_props = pd.concat(
    [df for df in df_ue_props_list])

# This code is a temporary fix--and should be safely removed
# once all employment calculations are rerun.
df_ue_props['age_range'] = df_ue_props['age_range'].replace(
{'Under 22':'21 or younger'})

df_ue_props.to_csv('Datasets/full_ue_props.csv', index = False)

In [122]:
df_ue_props['age_range'].value_counts()

age_range
All              442392
25-29             46689
30-34             46689
40-44             46689
55-59             46689
60 or older       46689
35-39             46686
45-49             46686
50-54             46683
22-24             45909
21 or younger     44892
Name: count, dtype: int64

In [123]:
df_ue_props

,period_val,occ2010,empstat_condensed,est,se,lci,uci,cv,df,n,error_upper,error_lower,est_as_pct,se_as_pct,lci_as_pct,uci_as_pct,error_upper_as_pct,error_lower_as_pct,prop_val_n,period,age_range
0,2026-Q3,Accountants and auditors,Employed,0.979711,0.005689,0.964942,0.988334,0.005806,568,1352,0.008622,0.014769,97.971119,0.568869,96.494200,98.833365,0.862247,1.476919,1327,year_and_quarter,All
1,2026-Q3,Accountants and auditors,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,568,1352,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0,year_and_quarter,All
2,2026-Q3,Accountants and auditors,Unemployed,0.020289,0.005689,0.011666,0.035058,0.280386,568,1352,0.014769,0.008622,2.028881,0.568869,1.166635,3.505800,1.476919,0.862247,25,year_and_quarter,All
3,2026-Q3,Actors,Employed,0.763722,0.071045,0.578196,0.884016,0.093025,12,43,0.120293,0.185526,76.372214,7.104545,57.819605,88.401557,12.029343,18.552609,32,year_and_quarter,All
4,2026-Q3,Actors,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,12,43,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0,year_and_quarter,All
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,2026-H2,Waiters and waitresses,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,1,29,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0,year_and_half,55-59
1457,2026-H2,Waiters and waitresses,Unemployed,0.058058,0.042485,0.000003,0.999163,0.731772,1,29,0.941105,0.058055,5.805768,4.248500,0.000318,99.916282,94.110514,5.805450,2,year_and_half,55-59
1458,2026-H2,Waiters and waitresses,Employed,0.927571,0.053804,0.694198,0.986348,0.058005,13,73,0.058777,0.233373,92.757116,5.380381,69.419844,98.634780,5.877664,23.337272,70,year_and_half,60 or older
1459,2026-H2,Waiters and waitresses,NILF_NIU,0.000000,0.000000,NaN,NaN,inf,13,73,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0,year_and_half,60 or older
1460,2026-H2,Waiters and waitresses,Unemployed,0.072429,0.053804,0.013652,0.305802,0.742851,13,73,0.233373,0.058777,7.242884,5.380381,1.365220,30.580156,23.337272,5.877664,3,year_and_half,60 or older

Adding an outcome variable that can be used for a logistic regression:

(Assigning a -1 value to those who are not in the labor force, or who don't meet the selection criteria for this question, is a reminder to remove them from our logistic-regression data.)

In [124]:
df_condensed['unemployed'] = df_condensed[
'empstat_condensed'].replace({'NILF_NIU':-1, 'Employed':0, 'Unemployed':1})

In [125]:
df_condensed['empstat_condensed'].value_counts()

empstat_condensed
NILF_NIU      11761484
Employed      11179445
Unemployed      638974
Name: count, dtype: int64

In [126]:
df_condensed['unemployed'].value_counts()

unemployed
-1    11761484
0     11179445
1       638974
Name: count, dtype: int64

## Saving our revised microdata table data to a CSV file for use within other analyses

Note: Polars is **much** faster at exporting large CSV files than is Pandas. (The following export task took around 5 seconds with Polars, including the Pandas-to-Polars DataFrame conversion, but roughly 142 seconds within Pandas.

In [127]:
pl.DataFrame(df_condensed).write_csv('/home/kjb3/D1V1/kjb3largefiles/large_programming/\
datasets/cps/cps_employment_trends_revised.csv')

In [128]:
end_time = time.time()
print(f"{datetime.now().isoformat(sep = ' ', 
timespec = 'seconds')}: The script finished running in {
round(end_time - start_time, 3)} seconds.")

2026-10-18 08:12:58: The script finished running in 30921.044 seconds.